services:

  database:
    build: database
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE=/run/secrets/database-password
    secrets:
      - source: target-database-password
        target: database-password
    networks:
      - database
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql

  cql-on-omop:
    build: cql-on-omop
    env_file: databases.env
    secrets:
      - source-database-password
      - target-database-password
    stop_signal: SIGQUIT
    networks:
      - database
    depends_on:
      - database

networks:
  database:
    external: no

volumes:
  data:
    external: no

secrets:
  source-database-password:
    file: source-database-password
  target-database-password:
    file: target-database-password
