FROM localhost/indicate-data-exchange-client
# docker.io/debian:stable

RUN DEBIAN_FRONTEND=noninteractive apt-get --assume-yes update     \
    && DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install \
         uuid                                                      \
    && apt-get clean

COPY --chmod=755 run-data-exchange.sh /app/run-data-exchange.sh

WORKDIR /app

CMD [ "/app/run-data-exchange.sh" ]

#HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
#  CMD curl TODO exit 1
