FROM ghcr.io/umg-minai/indicate-data-exchange-client:1.2.0

RUN DEBIAN_FRONTEND=noninteractive apt-get --assume-yes update     \
    && DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install \
         uuid                                                      \
    && apt-get clean

COPY --chmod=755 run-data-exchange.sh /app/run-data-exchange.sh

WORKDIR /app

CMD [ "/app/run-data-exchange.sh" ]
