// This file has been generated automatically from
// https://raw.githubusercontent.com/indicate-eu/data-dictionary-content/refs/heads/main/docs/data.json
// Concept set(s)
// * Acenocoumarol (2 entries) [modified 2026-02-12]
// * Apixaban (4 entries) [modified 2026-02-12]
// * Argatroban (9 entries) [modified 2026-02-12]
// * Bemiparin (10 entries) [modified 2026-02-12]
// * Betrixaban (2 entries) [modified 2026-02-12]
// * Bivalirudin (7 entries) [modified 2026-02-12]
// * Clorindione (1 entries) [modified 2026-02-12]
// * Dabigatran Etexilate (9 entries) [modified 2026-02-12]
// * Dalteparin (47 entries) [modified 2026-02-12]
// * Danaparoid (4 entries) [modified 2026-02-12]
// * Desirudin (2 entries) [modified 2026-02-12]
// * Dicumarol (5 entries) [modified 2026-02-12]
// * Edoxaban (6 entries) [modified 2026-02-12]
// * Enoxaparin (25 entries) [modified 2026-02-12]
// * Fluindione (2 entries) [modified 2026-02-12]
// * Fondaparinux (6 entries) [modified 2026-02-12]
// * Heparin (303 entries) [modified 2026-02-12]
// * Lepirudin (5 entries) [modified 2026-02-12]
// * Melagatran (1 entries) [modified 2026-02-12]
// * Nadroparin (21 entries) [modified 2026-02-12]
// * Parnaparin (6 entries) [modified 2026-02-12]
// * Phenindione (3 entries) [modified 2026-02-12]
// * Phenprocoumon (4 entries) [modified 2026-02-12]
// * Reviparin (23 entries) [modified 2026-02-12]
// * Rivaroxaban (13 entries) [modified 2026-02-12]
// * Sulodexide (1 entries) [modified 2026-02-12]
// * Tinzaparin (26 entries) [modified 2026-02-12]
// * Tioclomarol (1 entries) [modified 2026-02-12]
// * Warfarin (35 entries) [modified 2026-02-12]
// * Ximelagatran (1 entries) [modified 2026-02-12]

// Do not edit

library "AnticoagulationDrugs"

include IndicateQiElements called E

code "AMNIOTIC FLUID (BOVINE) 11 X / Bos taurus brain preparation 10 X / Bos taurus ovary preparation 11 X / Bos taurus placenta preparation 10 X / Bos taurus spleen preparation 11 X / Bos taurus testicle preparation 10 X / ... Delayed Release Oral Capsule": '43689326' from E.OMOPSV
code "Aesculus hippocastanum bark extract 0.05 MG/MG / heparin 0.05 UNT/MG / Thiamine 0.0025 MG/MG Topical Ointment": '41088162' from E.OMOPSV
code "Aesculus hippocastanum bark extract 0.0501 MG/MG / heparin 0.0501 UNT/MG / Thiamine 0.0025 MG/MG Topical Ointment": '42711564' from E.OMOPSV
code "Allantoin 0.0025 MG/MG / dexpanthenol 0.0025 MG/MG / heparin 0.12 UNT/MG / Oxyphenbutazone 0.03 MG/MG Topical Cream": '41119348' from E.OMOPSV
code "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.3 UNT/MG Topical Gel": '40869592' from E.OMOPSV
code "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.3 UNT/MG Topical Ointment": '41181942' from E.OMOPSV
code "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.5 UNT/MG Topical Ointment": '41213308' from E.OMOPSV
code "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.501 UNT/MG Topical Ointment": '42727370' from E.OMOPSV
code "Allantoin 0.003 MG/MG / dexpanthenol 0.05 MG/MG / heparin 0.1 UNT/MG / Hydrocortisone 0.0025 MG/MG / Procaine 0.002 MG/MG Topical Ointment": '41150908' from E.OMOPSV
code "Allantoin 0.008 MG/MG / heparin 0.03 UNT/MG / Hexachlorophene 0.02 MG/MG / Ichtyolammonium 0.025 MG/MG / Sulfur 0.1 MG/MG / Zinc Oxide 0.15 MG/MG Topical Cream": '40963063' from E.OMOPSV
code "Allantoin 0.01 MG/MG / Allium cepa whole extract 0.1 MG/MG / heparin 0.05 UNT/MG Topical Gel": '41244285' from E.OMOPSV
code "Allantoin 0.01 MG/MG / Allium cepa whole extract 0.1 MG/MG / heparin 0.0501 UNT/MG Topical Gel": '42722140' from E.OMOPSV
code "Allantoin 0.01 MG/MG / heparin 0.05 UNT/MG / Onion extract 0.1 MG/MG Vaginal Gel": '43708692' from E.OMOPSV
code "Allantoin 0.0333 MG/MG / Allium cepa whole extract 0.333 MG/MG / heparin 0.167 UNT/MG Topical Gel": '40838549' from E.OMOPSV
code "Allantoin 20 MG / Aluminum carbonate 12 MG / Bismuth 100 MG / dexpanthenol 100 MG / heparin 200 UNT / Hydrocortisone 5 MG / Procaine 4 MG Rectal Suppository": '40900730' from E.OMOPSV
code "Arnica extract 0.1 MG/MG / guaiazulene 0.00005 MG/MG / heparin 0.00004 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.00005 MG/MG Topical Gel": '41243987' from E.OMOPSV
code "Arnica extract 0.1 MG/MG / guaiazulene 0.00005 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.00005 MG/MG Topical Gel": '41305972' from E.OMOPSV
code "Arnica extract 0.1 MG/MG / guaiazulene 0.00005 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.00005 MG/MG Topical Ointment": '41150570' from E.OMOPSV
code "Arnica extract 0.1 MG/MG / guaiazulene 0.0000501 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.0000501 MG/MG Topical Gel": '42720822' from E.OMOPSV
code "Arnica extract 0.1 MG/MG / guaiazulene 0.0000501 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.0000501 MG/MG Topical Ointment": '42722171' from E.OMOPSV
code "Benzocaine 0.03 MG/MG / dexpanthenol 0.025 MG/MG / heparin 0.05 UNT/MG / Menthol 0.003 MG/MG / prednisolone 0.0005 MG/MG / Tyrothricin 0.001 MG/MG / Vitamin B 12 0.0001 MG/MG Topical Ointment": '41024775' from E.OMOPSV
code "Benzocaine 60 MG / dexpanthenol 50 MG / heparin 200 UNT / Menthol 0.05 MG / prednisolone 2 MG / Vitamin B 12 0.4 MG Rectal Suppository": '40869058' from E.OMOPSV
code "Benzocaine 900 MG / dexpanthenol 750 MG / heparin 2500 UNT / Menthol 30 MG / prednisolone 25 MG / Tyrothricin 10 MG / Vitamin B 12 5 MG Rectal Suppository": '40869057' from E.OMOPSV
code "Benzocaine 900 MG / dexpanthenol 750 MG / heparin 2500 UNT / Menthol 30 MG / prednisolone 70 MG / Tyrothricin 10 MG / Vitamin B 12 5 MG Rectal Suppository": '41024776' from E.OMOPSV
code "Certoparin": '19016072' from E.OMOPSV
code "Citric Acid 0.37 MG/ML / heparin 2 UNT/ML / Sodium Chloride 9 MG/ML / Sodium Phosphate, Dibasic 4.3 MG/ML Injection": '44071751' from E.OMOPSV
code "Citric Acid 1 MG/ML / Glucose 50 MG/ML / heparin 50 UNT/ML / Sodium Phosphate, Dibasic 4.1 MG/ML Injection": '44045916' from E.OMOPSV
code "Clorindione 2 MG Oral Tablet": '40993001' from E.OMOPSV
code "Dalteparin 10 UNT/ML Injectable Solution": '41054962' from E.OMOPSV
code "Dalteparin 100 MG/ML Injectable Solution": '36894581' from E.OMOPSV
code "Dalteparin 1000 UNT/ML Injectable Solution": '41117763' from E.OMOPSV
code "Dalteparin 1000 UNT/ML Prefilled Syringe": '35153406' from E.OMOPSV
code "Dalteparin 10000 UNT/ML Injection": '43263317' from E.OMOPSV
code "Dalteparin 12.5 UNT/ML Injectable Solution": '40868000' from E.OMOPSV
code "Dalteparin 12.5 UNT/ML Prefilled Syringe": '41211730' from E.OMOPSV
code "Dalteparin 12500 UNT/ML Injectable Solution": '43623979' from E.OMOPSV
code "Dalteparin 12500 UNT/ML Injection": '43290508' from E.OMOPSV
code "Dalteparin 12500000 UNT/ML Prefilled Syringe": '41273546' from E.OMOPSV
code "Dalteparin 2.5 UNT/ML Injectable Solution": '40868003' from E.OMOPSV
code "Dalteparin 2.5 UNT/ML Prefilled Syringe": '41242646' from E.OMOPSV
code "Dalteparin 226 MG/ML Injectable Solution": '42731154' from E.OMOPSV
code "Dalteparin 227 MG/ML Injectable Solution": '36880992' from E.OMOPSV
code "Dalteparin 228 MG/ML Injectable Solution": '42716535' from E.OMOPSV
code "Dalteparin 24 UNT/ML Prefilled Syringe": '41273544' from E.OMOPSV
code "Dalteparin 25 UNT/ML Injectable Solution": '40868001' from E.OMOPSV
code "Dalteparin 25 UNT/ML Prefilled Syringe": '41117765' from E.OMOPSV
code "Dalteparin 250 UNT/ML Prefilled Syringe": '35134341' from E.OMOPSV
code "Dalteparin 2500 UNT/ML Injection": '44045837' from E.OMOPSV
code "Dalteparin 2500 UNT/ML Prefilled Syringe": '42482044' from E.OMOPSV
code "Dalteparin 25000 UNT/ML Injection": '43268801' from E.OMOPSV
code "Dalteparin 36000 IU/ML Prefilled Syringe": '42875889' from E.OMOPSV
code "Dalteparin 5000 UNT Injectable Solution": '35158595' from E.OMOPSV
code "Dalteparin 5000 UNT/ML Prefilled Syringe": '40961514' from E.OMOPSV
code "Dalteparin 6250 UNT/ML Injectable Solution": '41023718' from E.OMOPSV
code "Dalteparin 900 MG/ML Injectable Solution": '36891680' from E.OMOPSV
code "Dexamethasone 0.0002 MG/MG / heparin 0.05 UNT/MG / Sodium Ichtosylate 0.06 MG/MG Topical Cream": '41180273' from E.OMOPSV
code "Diclofenac 0.00001 MG/MG / heparin 0.4 UNT/MG Transdermal System": '43023167' from E.OMOPSV
code "Diclofenac 0.01 MG/MG / heparin 0.4 UNT/MG Transdermal System": '43134660' from E.OMOPSV
code "Dihydroergotamine 0.5 MG / heparin 5000 UNT Prefilled Syringe": '41054768' from E.OMOPSV
code "Dihydroergotamine 0.714 MG/ML / heparin 7500 UNT/ML / Lidocaine 10 MG/ML Injectable Solution": '40961317' from E.OMOPSV
code "Dihydroergotamine 0.714 MG/ML / heparin 7500 UNT/ML Injectable Solution": '40961318' from E.OMOPSV
code "Dihydroergotamine 1 MG/ML / heparin 5000 UNT/ML / Lidocaine 10 MG/ML Injectable Solution": '40867800' from E.OMOPSV
code "Enoxaparin 1 UNT/ML Injectable Solution": '41148892' from E.OMOPSV
code "Enoxaparin 10 MG/ML Injectable Solution": '40867638' from E.OMOPSV
code "Enoxaparin 10 UNT/ML Injectable Solution": '41023342' from E.OMOPSV
code "Enoxaparin 10 UNT/ML Prefilled Syringe": '40961166' from E.OMOPSV
code "Enoxaparin 100 MG/ML Injection": '36881946' from E.OMOPSV
code "Enoxaparin 10000 UNT/ML Injectable Solution": '43803627' from E.OMOPSV
code "Enoxaparin 10000 UNT/ML Prefilled Syringe": '41211417' from E.OMOPSV
code "Enoxaparin 13.3 UNT/ML Prefilled Syringe": '40836551' from E.OMOPSV
code "Enoxaparin 133 MG/ML Prefilled Syringe": '41054605' from E.OMOPSV
code "Enoxaparin 15 UNT/ML Prefilled Syringe": '41054606' from E.OMOPSV
code "Enoxaparin 150 MG/ML Injectable Solution": '44123442' from E.OMOPSV
code "Enoxaparin 150 MG/ML Injection": '36886730' from E.OMOPSV
code "Enoxaparin 15000 UNT/ML Injectable Solution": '36259706' from E.OMOPSV
code "Enoxaparin 15000 UNT/ML Prefilled Syringe": '36783760' from E.OMOPSV
code "Enoxaparin 20 MG/ML Injectable Solution": '40929839' from E.OMOPSV
code "Enoxaparin 30 UNT/ML Prefilled Syringe": '40898729' from E.OMOPSV
code "Enoxaparin 33.3 MG/ML Injectable Solution": '41148895' from E.OMOPSV
code "Enoxaparin 5 UNT/ML Prefilled Syringe": '41023347' from E.OMOPSV
code "Enoxaparin 6 UNT/ML Prefilled Syringe": '41211416' from E.OMOPSV
code "Enoxaparin 7.5 UNT/ML Prefilled Syringe": '40836552' from E.OMOPSV
code "Escin 0.01 MG/MG / heparin 0.00005 UNT/MG / Salicylic Acid 0.05 MG/MG Topical Gel": '41273129' from E.OMOPSV
code "Escin 0.01 MG/MG / heparin 0.0000501 UNT/MG / Salicylic Acid 0.05 MG/MG Topical Gel": '42729919' from E.OMOPSV
code "Escin 0.02 MG/MG / heparin 0.0001 UNT/MG / Phospholipids 0.01 MG/MG Topical Gel": '41086096' from E.OMOPSV
code "Flufenamic Acid 0.035 MG/MG / heparin 0.1 UNT/MG / Niacin 0.0125 MG/MG / Salicylic Acid 0.05 MG/MG Topical Ointment": '41148608' from E.OMOPSV
code "Gentamicin 0.02 MG/ML / heparin 3500 UNT/ML / Vancomycin 0.1 MG/ML Injectable Solution": '40754281' from E.OMOPSV
code "Glucose 50 MG/ML / heparin 100 UNT/ML Injection": '44071643' from E.OMOPSV
code "Glucose 50 MG/ML / heparin 40 UNT/ML Injectable Solution": '44058816' from E.OMOPSV
code "Glucose 50 MG/ML / heparin 40 UNT/ML Injection": '44084523' from E.OMOPSV
code "Glucose 50 MG/ML / heparin 50 UNT/ML Injection": '44110321' from E.OMOPSV
code "Melagatran 10 MG/ML Prefilled Syringe": '40866445' from E.OMOPSV
code "Nadroparin 10 UNT/ML Prefilled Syringe": '41240930' from E.OMOPSV
code "Nadroparin 100 MG/ML Injectable Solution": '43786302' from E.OMOPSV
code "Nadroparin 11.4 UNT/ML Prefilled Syringe": '41021916' from E.OMOPSV
code "Nadroparin 19 UNT/ML Prefilled Syringe": '41053174' from E.OMOPSV
code "Nadroparin 190 MG/ML Injectable Solution": '43786295' from E.OMOPSV
code "Nadroparin 1900 UNT/ML Injectable Solution": '41147479' from E.OMOPSV
code "Nadroparin 19000 UNT/ML Injection": '43275002' from E.OMOPSV
code "Nadroparin 19000 UNT/ML Prefilled Syringe": '36883845' from E.OMOPSV
code "Nadroparin 25.3 UNT/ML Prefilled Syringe": '40959721' from E.OMOPSV
code "Nadroparin 633 UNT/ML Injectable Solution": '41021915' from E.OMOPSV
code "Nadroparin 8.6 UNT/ML Prefilled Syringe": '40866226' from E.OMOPSV
code "Nadroparin 9.5 UNT/ML Injectable Solution": '41084729' from E.OMOPSV
code "Nadroparin 9.5 UNT/ML Prefilled Syringe": '40959720' from E.OMOPSV
code "Nadroparin 9.53 UNT/ML Injectable Solution": '42728545' from E.OMOPSV
code "Nadroparin 9500 UNT/ML Injection": '43275004' from E.OMOPSV
code "Nadroparin 9500 UNT/ML Prefilled Syringe": '36894582' from E.OMOPSV
code "Phenprocoumon 1.5 MG Oral Tablet": '43837037' from E.OMOPSV
code "Phenprocoumon 10 MG/ML Injectable Solution": '41302483' from E.OMOPSV
code "Warfarin 0.02 MG/ML Oral Solution": '21134742' from E.OMOPSV
code "Warfarin 0.1 MG/ML Oral Solution": '21124844' from E.OMOPSV
code "Warfarin 0.2 MG/ML Oral Solution": '21066141' from E.OMOPSV
code "Warfarin 0.2 MG/ML Oral Suspension": '21174173' from E.OMOPSV
code "Warfarin 0.3 MG/ML Oral Solution": '21095537' from E.OMOPSV
code "Warfarin 0.4 MG/ML Oral Solution": '21105427' from E.OMOPSV
code "Warfarin 0.4 MG/ML Oral Suspension": '21036677' from E.OMOPSV
code "Warfarin 0.5 MG/ML Oral Solution": '21174174' from E.OMOPSV
code "Warfarin 0.6 MG/ML Oral Solution": '21105428' from E.OMOPSV
code "Warfarin 0.6 MG/ML Oral Suspension": '21164395' from E.OMOPSV
code "Warfarin 0.8 MG/ML Oral Solution": '21134748' from E.OMOPSV
code "Warfarin 0.832 MG/ML Oral Solution": '21134735' from E.OMOPSV
code "Warfarin 1 MG Oral Capsule": '40753383' from E.OMOPSV
code "Warfarin 1 MG/ML Oral Solution": '21046557' from E.OMOPSV
code "Warfarin 1 MG/ML Oral Suspension": '21026882' from E.OMOPSV
code "Warfarin 2 MG/ML Oral Granules": '35146532' from E.OMOPSV
code "Warfarin 2 MG/ML Oral Solution": '21115242' from E.OMOPSV
code "Warfarin 2 MG/ML Oral Suspension": '21174175' from E.OMOPSV
code "Warfarin 3 MG Oral Capsule": '40753374' from E.OMOPSV
code "Warfarin 5 MG Injectable Suspension": '44096725' from E.OMOPSV
code "Warfarin 5 MG Oral Capsule": '40753366' from E.OMOPSV
code "Warfarin 5 MG/ML Oral Solution": '21105415' from E.OMOPSV
code "Ximelagatran 24 MG Oral Tablet": '40896006' from E.OMOPSV
code "acenocoumarol 1 MG Oral Tablet": '19060033' from E.OMOPSV
code "acenocoumarol 4 MG Oral Tablet": '19060034' from E.OMOPSV
code "alpha Tocopherol 3 MG / Desonide 0.5 MG / heparin 500 UNT / Lidocaine 10 MG / Ruscosides 20 MG / Vitamin A 5000 UNT Rectal Suppository": '43134659' from E.OMOPSV
code "apixaban 2.5 MG Delayed Release Oral Tablet": '43139238' from E.OMOPSV
code "apixaban 2.5 MG Oral Tablet": '43013026' from E.OMOPSV
code "apixaban 5 MG Delayed Release Oral Tablet": '43139239' from E.OMOPSV
code "apixaban 5 MG Oral Tablet": '43013030' from E.OMOPSV
code "argatroban 0.5 MG/ML Injectable Solution": '42966022' from E.OMOPSV
code "argatroban 0.5 MG/ML Prefilled Syringe": '35140140' from E.OMOPSV
code "argatroban 1 MG/ML Injectable Solution": '40747299' from E.OMOPSV
code "argatroban 1 MG/ML Injection": '40220927' from E.OMOPSV
code "argatroban 100 MG/ML Injectable Solution": '41213021' from E.OMOPSV
code "argatroban 100 MG/ML Injection": '40220925' from E.OMOPSV
code "argatroban 100 MG/ML Prefilled Syringe": '42480206' from E.OMOPSV
code "argatroban 40 MG/ML Injectable Solution": '40962802' from E.OMOPSV
code "argatroban 5 MG/ML Injectable Solution": '42966026' from E.OMOPSV
code "bemiparin 125 MG/ML Prefilled Syringe": '42925118' from E.OMOPSV
code "bemiparin 12500 UNT/ML Injectable Solution": '36404328' from E.OMOPSV
code "bemiparin 175 MG/ML Prefilled Syringe": '42925114' from E.OMOPSV
code "bemiparin 17500 UNT/ML Injectable Solution": '36405848' from E.OMOPSV
code "bemiparin 25000 UNT/ML Injectable Solution": '36405849' from E.OMOPSV
code "bemiparin sodium 12500 UNT/ML Prefilled Syringe": '42902423' from E.OMOPSV
code "bemiparin sodium 17500 UNT/ML Prefilled Syringe": '42902551' from E.OMOPSV
code "bemiparin sodium 22500 UNT/ML Prefilled Syringe": '42902773' from E.OMOPSV
code "bemiparin sodium 25000 UNT/ML Prefilled Syringe": '42902628' from E.OMOPSV
code "bemiparin sodium 40000 UNT/ML Prefilled Syringe": '42902724' from E.OMOPSV
code "betrixaban 40 MG Oral Capsule": '1592993' from E.OMOPSV
code "betrixaban 80 MG Oral Capsule": '1593001' from E.OMOPSV
code "bisabolol 0.003 MG/MG / heparin 0.0002 UNT/MG Topical Cream": '44187526' from E.OMOPSV
code "bisabolol 0.003 MG/MG / heparin 0.0002 UNT/MG Topical Ointment": '41085614' from E.OMOPSV
code "bivalirudin 100 MG Injection": '2912580' from E.OMOPSV
code "bivalirudin 25 MG/ML Injectable Solution": '43023767' from E.OMOPSV
code "bivalirudin 250 MG Injectable Solution": '41212596' from E.OMOPSV
code "bivalirudin 250 MG Injectable Suspension": '44059183' from E.OMOPSV
code "bivalirudin 250 MG Injection": '19074279' from E.OMOPSV
code "bivalirudin 250 MG Prefilled Syringe": '36888705' from E.OMOPSV
code "bivalirudin 5 MG/ML Injection": '793488' from E.OMOPSV
code "dabigatran etexilate 110 MG Oral Capsule": '35606208' from E.OMOPSV
code "dabigatran etexilate 110 MG Oral Pellet": '1758804' from E.OMOPSV
code "dabigatran etexilate 150 MG Oral Capsule": '40228154' from E.OMOPSV
code "dabigatran etexilate 150 MG Oral Pellet": '1758808' from E.OMOPSV
code "dabigatran etexilate 20 MG Oral Pellet": '1758811' from E.OMOPSV
code "dabigatran etexilate 30 MG Oral Pellet": '1758815' from E.OMOPSV
code "dabigatran etexilate 40 MG Oral Pellet": '1758819' from E.OMOPSV
code "dabigatran etexilate 50 MG Oral Pellet": '1758823' from E.OMOPSV
code "dabigatran etexilate 75 MG Oral Capsule": '40228161' from E.OMOPSV
code "dalteparin 10000 IU/ML Injectable Solution": '2068884' from E.OMOPSV
code "dalteparin 10000 IU/ML Injection": '2927919' from E.OMOPSV
code "dalteparin 12500 IU/ML Injectable Solution": '35869695' from E.OMOPSV
code "dalteparin 12500 IU/ML Injection": '2927914' from E.OMOPSV
code "dalteparin 12500 IU/ML Prefilled Syringe": '2068880' from E.OMOPSV
code "dalteparin 2500 IU/ML Injectable Solution": '2068887' from E.OMOPSV
code "dalteparin 25000 IU/ML Injectable Solution": '35869692' from E.OMOPSV
code "dalteparin 25000 IU/ML Injection": '2927906' from E.OMOPSV
code "dalteparin 25000 IU/ML Prefilled Syringe": '2068876' from E.OMOPSV
code "dalteparin 55.2 MG/ML Injectable Solution": '19131463' from E.OMOPSV
code "dalteparin 75 MG/ML Injectable Solution": '19104360' from E.OMOPSV
code "dalteparin sodium 10000 UNT/ML Injectable Solution": '40176336' from E.OMOPSV
code "dalteparin sodium 10000 UNT/ML Prefilled Syringe": '42902583' from E.OMOPSV
code "dalteparin sodium 12500 UNT/ML Prefilled Syringe": '42903352' from E.OMOPSV
code "dalteparin sodium 2500 UNT/ML Injectable Solution": '40176344' from E.OMOPSV
code "dalteparin sodium 2500 UNT/ML Injection": '741765' from E.OMOPSV
code "dalteparin sodium 25000 UNT/ML Injectable Solution": '40176348' from E.OMOPSV
code "dalteparin sodium 25000 UNT/ML Prefilled Syringe": '42902755' from E.OMOPSV
code "dalteparin sodium 36 MG/ML / dihydroergotamine mesylate 1 MG/ML Injectable Solution": '42707445' from E.OMOPSV
code "dalteparin sodium 36 MG/ML Injectable Solution": '19104359' from E.OMOPSV
code "danaparoid 1250 IU/ML Injection": '2913859' from E.OMOPSV
code "danaparoid 1250 UNT/ML Injectable Solution": '19076071' from E.OMOPSV
code "danaparoid 1250 UNT/ML Injection": '43285310' from E.OMOPSV
code "danaparoid 1250 UNT/ML Prefilled Syringe": '42479142' from E.OMOPSV
code "desirudin 15 MG Injectable Solution": '41149199' from E.OMOPSV
code "desirudin 15 MG Injection": '19102223' from E.OMOPSV
code "dexpanthenol 0.025 MG/MG / Dimethyl Sulfoxide 0.15 MG/MG / heparin 0.0005 UNT/MG Topical Gel": '40930105' from E.OMOPSV
code "dexpanthenol 0.025 MG/MG / Dimethyl Sulfoxide 0.15 MG/MG / heparin 0.0005 UNT/MG Urethral Suppository": '40836781' from E.OMOPSV
code "dexpanthenol 0.025 MG/MG / Dimethyl Sulfoxide 0.15 MG/MG / heparin 0.000501 UNT/MG Topical Gel": '42712662' from E.OMOPSV
code "dicumarol 100 MG Oral Tablet": '19108504' from E.OMOPSV
code "dicumarol 25 MG Oral Capsule": '19108493' from E.OMOPSV
code "dicumarol 25 MG Oral Tablet": '1325125' from E.OMOPSV
code "dicumarol 50 MG Oral Capsule": '19108503' from E.OMOPSV
code "dicumarol 50 MG Oral Tablet": '19076408' from E.OMOPSV
code "edoxaban 15 MG Delayed Release Oral Tablet": '36787912' from E.OMOPSV
code "edoxaban 15 MG Disintegrating Oral Tablet": '35141149' from E.OMOPSV
code "edoxaban 30 MG Delayed Release Oral Tablet": '36787920' from E.OMOPSV
code "edoxaban 30 MG Disintegrating Oral Tablet": '35137111' from E.OMOPSV
code "edoxaban 60 MG Delayed Release Oral Tablet": '36787907' from E.OMOPSV
code "edoxaban 60 MG Disintegrating Oral Tablet": '35137677' from E.OMOPSV
code "enoxaparin 10000 IU/ML Injectable Solution": '35869699' from E.OMOPSV
code "enoxaparin 60 MG/ML Injectable Solution": '19104488' from E.OMOPSV
code "enoxaparin sodium 100 MG/ML Injectable Solution": '40160948' from E.OMOPSV
code "enoxaparin sodium 100 MG/ML Prefilled Syringe": '42902906' from E.OMOPSV
code "enoxaparin sodium 150 MG/ML Prefilled Syringe": '42902627' from E.OMOPSV
code "ethylene glycol 0.05 MG/MG / heparin 0.0005 UNT/MG Topical Gel": '40836390' from E.OMOPSV
code "ethylene glycol 0.0501 MG/MG / heparin 0.000501 UNT/MG Topical Gel": '42712754' from E.OMOPSV
code "factor IX 30 UNT/ML / factor VII 24 UNT/ML / factor X 30 UNT/ML / heparin 12.5 UNT/ML / Prothrombin 30 UNT/ML Injectable Solution": '41179762' from E.OMOPSV
code "factor IX 600 UNT / factor VII 500 UNT / factor X 600 UNT / heparin 250 UNT / Prothrombin 600 UNT Injectable Solution": '41179763' from E.OMOPSV
code "fluindione 20 MG Extended Release Oral Tablet": '19134706' from E.OMOPSV
code "fluindione 20 MG Oral Tablet": '43147543' from E.OMOPSV
code "fondaparinux 12.5 MG/ML Injectable Solution": '44084416' from E.OMOPSV
code "fondaparinux 12.5 MG/ML Injection": '43266627' from E.OMOPSV
code "fondaparinux 5 MG/ML Injectable Solution": '44058691' from E.OMOPSV
code "fondaparinux 5 MG/ML Injection": '43282915' from E.OMOPSV
code "fondaparinux sodium 12.5 MG/ML Prefilled Syringe": '42902397' from E.OMOPSV
code "fondaparinux sodium 5 MG/ML Prefilled Syringe": '42903069' from E.OMOPSV
code "glycol salicylate 0.05 MG/MG / heparin 0.5 UNT/MG / LEVOMENTHOL 0.005 MG/MG Vaginal Gel": '43833542' from E.OMOPSV
code "glycol salicylate 0.05 MG/MG / heparin 0.5 UNT/MG Vaginal Gel": '43708208' from E.OMOPSV
code "heparin 0.00005 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel": '41303737' from E.OMOPSV
code "heparin 0.00005 UNT/MG / polidocanol 0.03 MG/MG Topical Gel": '41116816' from E.OMOPSV
code "heparin 0.00005 UNT/MG Topical Gel": '41085619' from E.OMOPSV
code "heparin 0.00005 UNT/MG Topical Ointment": '41116820' from E.OMOPSV
code "heparin 0.0000501 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel": '42724659' from E.OMOPSV
code "heparin 0.0000501 UNT/MG / polidocanol 0.03 MG/MG Topical Gel": '42713874' from E.OMOPSV
code "heparin 0.0000501 UNT/MG Topical Gel": '42724572' from E.OMOPSV
code "heparin 0.00015 UNT/MG Topical Gel": '41022767' from E.OMOPSV
code "heparin 0.000167 UNT/MG / LEVOMENTHOL 0.0017 MG/MG / Salicylic Acid 0.017 MG/MG Topical Gel": '40867045' from E.OMOPSV
code "heparin 0.0003 UNT/MG Topical Cream": '40960616' from E.OMOPSV
code "heparin 0.0003 UNT/MG Topical Gel": '41210854' from E.OMOPSV
code "heparin 0.0003 UNT/MG Topical Ointment": '41272598' from E.OMOPSV
code "heparin 0.0004 UNT/MG Topical Gel": '40929299' from E.OMOPSV
code "heparin 0.0004 UNT/MG Topical Ointment": '41179393' from E.OMOPSV
code "heparin 0.0005 UNT/MG / LEVOMENTHOL 0.00002 MG/MG / Salicylic Acid 0.001 MG/MG Topical Gel": '41148306' from E.OMOPSV
code "heparin 0.0005 UNT/MG / LEVOMENTHOL 0.005 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel": '40991831' from E.OMOPSV
code "heparin 0.0005 UNT/MG Topical Gel": '40898178' from E.OMOPSV
code "heparin 0.0005 UNT/MG Topical Ointment": '40835976' from E.OMOPSV
code "heparin 0.000501 UNT/MG / LEVOMENTHOL 0.00002 MG/MG / Salicylic Acid 0.001 MG/MG Topical Gel": '42718019' from E.OMOPSV
code "heparin 0.000501 UNT/MG / LEVOMENTHOL 0.00501 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel": '42731274' from E.OMOPSV
code "heparin 0.000501 UNT/MG Topical Gel": '42728590' from E.OMOPSV
code "heparin 0.000501 UNT/MG Topical Ointment": '42719249' from E.OMOPSV
code "heparin 0.00056 UNT/MG Topical Gel": '41054056' from E.OMOPSV
code "heparin 0.00056 UNT/MG Topical Ointment": '40991847' from E.OMOPSV
code "heparin 0.0006 UNT/MG Topical Cream": '40991849' from E.OMOPSV
code "heparin 0.0006 UNT/MG Topical Gel": '41179401' from E.OMOPSV
code "heparin 0.0006 UNT/MG Topical Ointment": '41179402' from E.OMOPSV
code "heparin 0.001 MG/MG / Zinc Sulfate 0.005 MG/MG Vaginal Gel": '43743931' from E.OMOPSV
code "heparin 0.001 MG/MG Vaginal Gel": '43654840' from E.OMOPSV
code "heparin 0.001 UNT/MG Topical Gel": '41272584' from E.OMOPSV
code "heparin 0.001 UNT/MG Topical Ointment": '41179385' from E.OMOPSV
code "heparin 0.0015 UNT/MG Topical Gel": '40929302' from E.OMOPSV
code "heparin 0.0015 UNT/MG Topical Ointment": '41272593' from E.OMOPSV
code "heparin 0.00151 UNT/MG Topical Gel": '42723266' from E.OMOPSV
code "heparin 0.0018 UNT/MG Topical Gel": '41054053' from E.OMOPSV
code "heparin 0.0018 UNT/MG Topical Ointment": '40835975' from E.OMOPSV
code "heparin 0.002 UNT/ML / Sodium Chloride 0.009 MG/ML Injection": '43284796' from E.OMOPSV
code "heparin 0.003 UNT/MG Topical Gel": '40991836' from E.OMOPSV
code "heparin 0.003 UNT/MG Topical Ointment": '40929295' from E.OMOPSV
code "heparin 0.00313 MG/MG Vaginal Gel": '43852795' from E.OMOPSV
code "heparin 0.00417 MG/MG Vaginal Gel": '43690826' from E.OMOPSV
code "heparin 0.00418 MG/MG Vaginal Gel": '42728589' from E.OMOPSV
code "heparin 0.005 UNT/MG / Salicylic Acid 0.02 MG/MG Topical Ointment": '41116815' from E.OMOPSV
code "heparin 0.005 UNT/MG Topical Gel": '41022761' from E.OMOPSV
code "heparin 0.005 UNT/MG Topical Ointment": '41241729' from E.OMOPSV
code "heparin 0.00501 UNT/MG / Salicylic Acid 0.02 MG/MG Topical Ointment": '42720596' from E.OMOPSV
code "heparin 0.00501 UNT/MG Topical Gel": '42731188' from E.OMOPSV
code "heparin 0.00501 UNT/MG Topical Ointment": '42719250' from E.OMOPSV
code "heparin 0.00543 MG/MG Vaginal Gel": '43762517' from E.OMOPSV
code "heparin 0.00544 MG/MG Vaginal Gel": '42721959' from E.OMOPSV
code "heparin 0.006 UNT/MG Topical Gel": '41210830' from E.OMOPSV
code "heparin 0.006 UNT/MG Topical Ointment": '40898166' from E.OMOPSV
code "heparin 0.0075 UNT/MG Topical Gel": '41148321' from E.OMOPSV
code "heparin 0.0075 UNT/MG Topical Ointment": '40835973' from E.OMOPSV
code "heparin 0.01 UNT/MG Topical Gel": '41210837' from E.OMOPSV
code "heparin 0.01 UNT/MG Topical Ointment": '41116819' from E.OMOPSV
code "heparin 0.012 MG/MG Vaginal Gel": '43618682' from E.OMOPSV
code "heparin 0.012 UNT/MG Topical Gel": '41116829' from E.OMOPSV
code "heparin 0.015 UNT/MG Topical Gel": '41272599' from E.OMOPSV
code "heparin 0.015 UNT/MG Topical Ointment": '41085635' from E.OMOPSV
code "heparin 0.018 UNT/MG Topical Gel": '41303748' from E.OMOPSV
code "heparin 0.018 UNT/MG Topical Ointment": '40867055' from E.OMOPSV
code "heparin 0.025 UNT/MG Topical Gel": '41085621' from E.OMOPSV
code "heparin 0.025 UNT/MG Topical Ointment": '41210841' from E.OMOPSV
code "heparin 0.03 UNT/MG Topical Gel": '41210844' from E.OMOPSV
code "heparin 0.03 UNT/MG Topical Ointment": '41210845' from E.OMOPSV
code "heparin 0.045 UNT/MG Topical Gel": '41148310' from E.OMOPSV
code "heparin 0.045 UNT/MG Topical Ointment": '40929293' from E.OMOPSV
code "heparin 0.05 UNT/MG / Hydrocortisone 0.0033 MG/MG / polidocanol 0.03 MG/MG / Thiamine 0.001 MG/MG / Tyrothricin 0.001 MG/MG / Vitamin A 0.33 UNT/MG / Vitamin E 0.001 MG/MG Topical Ointment": '41022758' from E.OMOPSV
code "heparin 0.05 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel": '40898163' from E.OMOPSV
code "heparin 0.05 UNT/MG / Melilotus extract 0.001 MG/MG Topical Cream": '43167730' from E.OMOPSV
code "heparin 0.05 UNT/MG / Menthol 0.02 MG/MG / Pinus sylvestris bark extract 0.024 MG/MG Topical Ointment": '41241726' from E.OMOPSV
code "heparin 0.05 UNT/MG Topical Ointment": '40898179' from E.OMOPSV
code "heparin 0.0501 UNT/MG / Hydrocortisone 0.0033 MG/MG / polidocanol 0.03 MG/MG / Thiamine 0.001 MG/MG / Tyrothricin 0.001 MG/MG / Vitamin A 0.33 UNT/MG / Vitamin E 0.001 MG/MG Topical Ointment": '42715481' from E.OMOPSV
code "heparin 0.0501 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel": '42724658' from E.OMOPSV
code "heparin 0.0501 UNT/MG / Menthol 0.02 MG/MG / Pinus sylvestris bark extract 0.024 MG/MG Topical Ointment": '42711403' from E.OMOPSV
code "heparin 0.0501 UNT/MG Topical Ointment": '42724570' from E.OMOPSV
code "heparin 0.06 UNT/MG Topical Gel": '41148320' from E.OMOPSV
code "heparin 0.06 UNT/MG Topical Ointment": '40867052' from E.OMOPSV
code "heparin 0.065 UNT/MG / polidocanol 0.03 MG/MG / prednisolone 0.00223 MG/MG Topical Ointment": '40991829' from E.OMOPSV
code "heparin 0.125 UNT/MG Topical Ointment": '41210848' from E.OMOPSV
code "heparin 0.15 UNT/MG Topical Gel": '40991839' from E.OMOPSV
code "heparin 0.15 UNT/MG Topical Ointment": '41085620' from E.OMOPSV
code "heparin 0.151 UNT/MG Topical Gel": '588904' from E.OMOPSV
code "heparin 0.175 UNT/MG / Zinc Oxide 0.005 MG/MG Topical Gel": '40929286' from E.OMOPSV
code "heparin 0.175 UNT/MG / Zinc Sulfate 0.005 MG/MG Topical Gel": '36262221' from E.OMOPSV
code "heparin 0.2 UNT/MG / LEVOMENTHOL 0.003 MG/MG Topical Cream": '43780648' from E.OMOPSV
code "heparin 0.2 UNT/MG Topical Cream": '43798583' from E.OMOPSV
code "heparin 0.2 UNT/MG Topical Gel": '41272591' from E.OMOPSV
code "heparin 0.2 UNT/MG Topical Ointment": '41179400' from E.OMOPSV
code "heparin 0.25 UNT/MG Topical Gel": '41054047' from E.OMOPSV
code "heparin 0.25 UNT/MG Topical Ointment": '40867049' from E.OMOPSV
code "heparin 0.3 UNT/MG / troxerutin 0.02 MG/MG Topical Ointment": '41148304' from E.OMOPSV
code "heparin 0.3 UNT/MG Topical Cream": '43672989' from E.OMOPSV
code "heparin 0.3 UNT/MG Topical Gel": '41303746' from E.OMOPSV
code "heparin 0.3 UNT/MG Topical Ointment": '43639795' from E.OMOPSV
code "heparin 0.3 UNT/MG Vaginal Gel": '43744655' from E.OMOPSV
code "heparin 0.4 UNT/MG Topical Cream": '41241736' from E.OMOPSV
code "heparin 0.4 UNT/MG Topical Gel": '41054049' from E.OMOPSV
code "heparin 0.4 UNT/MG Topical Ointment": '41241737' from E.OMOPSV
code "heparin 0.5 UNT/MG / Menthol 0.005 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel": '40960602' from E.OMOPSV
code "heparin 0.5 UNT/MG Topical Gel": '41116828' from E.OMOPSV
code "heparin 0.5 UNT/MG Topical Ointment": '43690816' from E.OMOPSV
code "heparin 0.5 UNT/MG Vaginal Gel": '43582627' from E.OMOPSV
code "heparin 0.501 UNT/MG / Menthol 0.005 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel": '42710219' from E.OMOPSV
code "heparin 0.501 UNT/MG Topical Gel": '42720597' from E.OMOPSV
code "heparin 0.501 UNT/MG Topical Ointment": '42719248' from E.OMOPSV
code "heparin 0.6 UNT/MG Topical Cream": '43708683' from E.OMOPSV
code "heparin 0.6 UNT/MG Topical Gel": '41210828' from E.OMOPSV
code "heparin 0.6 UNT/MG Topical Ointment": '43816622' from E.OMOPSV
code "heparin 0.6 UNT/MG Vaginal Gel": '43636806' from E.OMOPSV
code "heparin 0.65 UNT/ML Prefilled Applicator": '41148312' from E.OMOPSV
code "heparin 0.75 UNT/MG Topical Gel": '41241741' from E.OMOPSV
code "heparin 0.75 UNT/MG Topical Ointment": '40867058' from E.OMOPSV
code "heparin 0.8 UNT/MG Topical Ointment": '41272590' from E.OMOPSV
code "heparin 0.9 UNT/MG Topical Gel": '40898177' from E.OMOPSV
code "heparin 1 UNT/ML Injectable Solution": '21106100' from E.OMOPSV
code "heparin 1 UNT/ML Injection": '21037324' from E.OMOPSV
code "heparin 1.2 UNT/MG Stick": '41179386' from E.OMOPSV
code "heparin 1.2 UNT/MG Topical Cream": '41210836' from E.OMOPSV
code "heparin 1.2 UNT/MG Topical Gel": '41210835' from E.OMOPSV
code "heparin 1.2 UNT/MG Topical Ointment": '41179388' from E.OMOPSV
code "heparin 1.3 UNT/MG Ophthalmic Ointment": '40929294' from E.OMOPSV
code "heparin 1.5 UNT/MG Topical Cream": '41272580' from E.OMOPSV
code "heparin 1.5 UNT/MG Topical Gel": '40835960' from E.OMOPSV
code "heparin 1.5 UNT/MG Topical Ointment": '43780632' from E.OMOPSV
code "heparin 1.5 UNT/MG Vaginal Gel": '43618681' from E.OMOPSV
code "heparin 1.51 UNT/MG Vaginal Gel": '42713876' from E.OMOPSV
code "heparin 1.8 UNT/MG Topical Gel": '41241744' from E.OMOPSV
code "heparin 1.8 UNT/MG Topical Ointment": '43726629' from E.OMOPSV
code "heparin 1.8 UNT/MG Vaginal Gel": '43762526' from E.OMOPSV
code "heparin 10 UNT/ML Intraperitoneal Solution": '44058629' from E.OMOPSV
code "heparin 100 UNT/ML Irrigation Solution": '44110128' from E.OMOPSV
code "heparin 1000 IU/ML Injectable Solution": '2059333' from E.OMOPSV
code "heparin 1000 UNT/ML Topical Gel": '41210847' from E.OMOPSV
code "heparin 1000 UNT/ML Topical Ointment": '43690819' from E.OMOPSV
code "heparin 1000 UNT/ML Vaginal Gel": '43816621' from E.OMOPSV
code "heparin 10000 UNT Injectable Solution": '35136788' from E.OMOPSV
code "heparin 10000 UNT Topical Ointment": '35865902' from E.OMOPSV
code "heparin 10000 UNT/ML Prefilled Syringe": '41272586' from E.OMOPSV
code "heparin 100000 UNT Injectable Solution": '41148326' from E.OMOPSV
code "heparin 10300 IU/ML Injectable Solution": '35865898' from E.OMOPSV
code "heparin 114 UNT/ML Topical Gel": '40929298' from E.OMOPSV
code "heparin 120 UNT / polidocanol 30 MG / prednisolone 1.68 MG Rectal Suppository": '40960601' from E.OMOPSV
code "heparin 125000 UNT/ML Prefilled Syringe": '40929304' from E.OMOPSV
code "heparin 1300 UNT/ML Prefilled Applicator": '41085626' from E.OMOPSV
code "heparin 15 UNT/ML Injectable Solution": '40867051' from E.OMOPSV
code "heparin 15 UNT/ML Prefilled Syringe": '41303742' from E.OMOPSV
code "heparin 150 UNT/ML Injectable Solution": '35156166' from E.OMOPSV
code "heparin 150 UNT/ML Prefilled Syringe": '35145461' from E.OMOPSV
code "heparin 15000 UNT/ML Prefilled Syringe": '41148316' from E.OMOPSV
code "heparin 16700 UNT/ML Prefilled Syringe": '40960609' from E.OMOPSV
code "heparin 171 UNT/ML Topical Gel": '40867046' from E.OMOPSV
code "heparin 180000 UNT/ML Topical Gel": '41210829' from E.OMOPSV
code "heparin 2 IU/ML Injectable Solution": '2059340' from E.OMOPSV
code "heparin 2 UNT/ML / Sodium Chloride 9 MG/ML Injection": '43295634' from E.OMOPSV
code "heparin 2.4 UNT/MG Topical Cream": '41085624' from E.OMOPSV
code "heparin 2.4 UNT/MG Topical Gel": '41116823' from E.OMOPSV
code "heparin 2.4 UNT/MG Topical Ointment": '40835974' from E.OMOPSV
code "heparin 20 UNT/ML Injectable Solution": '41116821' from E.OMOPSV
code "heparin 200 UNT/ML Injectable Solution": '35158888' from E.OMOPSV
code "heparin 200 UNT/ML Prefilled Syringe": '35159877' from E.OMOPSV
code "heparin 2000 UNT/ML Injectable Solution": '44176289' from E.OMOPSV
code "heparin 20000 UNT Injectable Solution": '44045627' from E.OMOPSV
code "heparin 20000 UNT Topical Ointment": '41116818' from E.OMOPSV
code "heparin 20000 UNT/ML Prefilled Syringe": '40821113' from E.OMOPSV
code "heparin 25 UNT/ML Injectable Solution": '40824234' from E.OMOPSV
code "heparin 25 UNT/ML Prefilled Syringe": '41303739' from E.OMOPSV
code "heparin 250 UNT/ML Prefilled Syringe": '35135715' from E.OMOPSV
code "heparin 2500 UNT / polidocanol 900 MG / prednisolone 61.4 MG Rectal Suppository": '40929287' from E.OMOPSV
code "heparin 2500 UNT/ML Injectable Solution": '41116826' from E.OMOPSV
code "heparin 25000 UNT Injectable Solution": '41085628' from E.OMOPSV
code "heparin 25000 UNT/ML Injection": '36887721' from E.OMOPSV
code "heparin 250000 UNT Injectable Solution": '41210839' from E.OMOPSV
code "heparin 3 IU/MG Topical Gel": '37592067' from E.OMOPSV
code "heparin 30000 UNT Topical Gel": '41179397' from E.OMOPSV
code "heparin 31300 UNT/ML Injectable Solution": '41085627' from E.OMOPSV
code "heparin 350 UNT/ML Prefilled Syringe": '35149764' from E.OMOPSV
code "heparin 3500 IU Topical Gel": '35865892' from E.OMOPSV
code "heparin 5 UNT/ML Injectable Solution": '41303738' from E.OMOPSV
code "heparin 50 UNT/ML Vaginal Gel": '43852800' from E.OMOPSV
code "heparin 500 UNT/ML Injectable Solution": '41303747' from E.OMOPSV
code "heparin 500 UNT/ML Injection": '42483085' from E.OMOPSV
code "heparin 500 UNT/ML Prefilled Syringe": '35160519' from E.OMOPSV
code "heparin 5000 IU/ML Injectable Solution": '2059337' from E.OMOPSV
code "heparin 5000 UNT Injectable Solution": '44097262' from E.OMOPSV
code "heparin 5000 UNT Prefilled Syringe": '41179395' from E.OMOPSV
code "heparin 5000 UNT Topical Ointment": '35865905' from E.OMOPSV
code "heparin 5000 UNT/ML Ophthalmic Solution": '21047225' from E.OMOPSV
code "heparin 50000 UNT/ML Injectable Solution": '41272587' from E.OMOPSV
code "heparin 50000 UNT/ML Topical Gel": '40898172' from E.OMOPSV
code "heparin 5000000 UNT/ML Injectable Solution": '21145313' from E.OMOPSV
code "heparin 521 UNT/ML Injectable Solution": '35762233' from E.OMOPSV
code "heparin 521 UNT/ML Injection": '42480707' from E.OMOPSV
code "heparin 60 UNT/MG Topical Gel": '41085629' from E.OMOPSV
code "heparin 60000 UNT/ML Topical Gel": '41148313' from E.OMOPSV
code "heparin 60000 UNT/ML Topical Ointment": '41210833' from E.OMOPSV
code "heparin 650 UNT/ML Prefilled Applicator": '41054057' from E.OMOPSV
code "heparin 7000 UNT Topical Ointment": '35865886' from E.OMOPSV
code "heparin 750 UNT/ML Injectable Solution": '40867057' from E.OMOPSV
code "heparin 7500 UNT Prefilled Syringe": '41148309' from E.OMOPSV
code "heparin 80000 UNT/ML Prefilled Syringe": '41022763' from E.OMOPSV
code "heparin 83300 UNT/ML Prefilled Syringe": '40898168' from E.OMOPSV
code "heparin calcium 25000 UNT/ML Injectable Solution": '19135718' from E.OMOPSV
code "heparin calcium 25000 UNT/ML Prefilled Syringe": '42902723' from E.OMOPSV
code "heparin sodium, bovine 1000 UNT/ML Injectable Solution": '43011961' from E.OMOPSV
code "heparin sodium, bovine 10000 UNT/ML Injectable Solution": '43011963' from E.OMOPSV
code "heparin sodium, bovine 5000 UNT/ML Injectable Solution": '43011864' from E.OMOPSV
code "heparin sodium, porcine 0.25 UNT/ML Injectable Solution": '43011978' from E.OMOPSV
code "heparin sodium, porcine 1 UNT/ML Prefilled Syringe": '43011873' from E.OMOPSV
code "heparin sodium, porcine 10 UNT/ML Injectable Solution": '43011809' from E.OMOPSV
code "heparin sodium, porcine 10 UNT/ML Injection": '46275871' from E.OMOPSV
code "heparin sodium, porcine 10 UNT/ML Prefilled Syringe": '43011884' from E.OMOPSV
code "heparin sodium, porcine 100 UNT/ML Injectable Solution": '43011816' from E.OMOPSV
code "heparin sodium, porcine 100 UNT/ML Injection": '46275401' from E.OMOPSV
code "heparin sodium, porcine 100 UNT/ML Prefilled Syringe": '43011892' from E.OMOPSV
code "heparin sodium, porcine 1000 UNT/ML / taurolidine 13.5 MG/ML Injection": '747312' from E.OMOPSV
code "heparin sodium, porcine 1000 UNT/ML Injectable Solution": '43011826' from E.OMOPSV
code "heparin sodium, porcine 1000 UNT/ML Injection": '46275356' from E.OMOPSV
code "heparin sodium, porcine 1000 UNT/ML Prefilled Syringe": '43011903' from E.OMOPSV
code "heparin sodium, porcine 10000 UNT/ML Cartridge": '46275126' from E.OMOPSV
code "heparin sodium, porcine 10000 UNT/ML Injectable Solution": '43011962' from E.OMOPSV
code "heparin sodium, porcine 10000 UNT/ML Injection": '46275353' from E.OMOPSV
code "heparin sodium, porcine 10000 UNT/ML Prefilled Syringe": '1510953' from E.OMOPSV
code "heparin sodium, porcine 12500 UNT/ML Injectable Solution": '43011964' from E.OMOPSV
code "heparin sodium, porcine 15000 UNT/ML Injectable Solution": '43011969' from E.OMOPSV
code "heparin sodium, porcine 2 UNT/ML Injectable Solution": '43011966' from E.OMOPSV
code "heparin sodium, porcine 2 UNT/ML Injection": '46275377' from E.OMOPSV
code "heparin sodium, porcine 2.5 UNT/ML Injectable Solution": '43011836' from E.OMOPSV
code "heparin sodium, porcine 2000 UNT/ML Injection": '46275128' from E.OMOPSV
code "heparin sodium, porcine 2000 UNT/ML Prefilled Syringe": '43011901' from E.OMOPSV
code "heparin sodium, porcine 20000 UNT/ML Injectable Solution": '43011841' from E.OMOPSV
code "heparin sodium, porcine 250 UNT/ML Injectable Solution": '43011970' from E.OMOPSV
code "heparin sodium, porcine 2500 UNT/ML Injection": '46275127' from E.OMOPSV
code "heparin sodium, porcine 25000 UNT/ML Injectable Solution": '43011843' from E.OMOPSV
code "heparin sodium, porcine 3000 UNT/ML Injectable Solution": '43011971' from E.OMOPSV
code "heparin sodium, porcine 40 UNT/ML Injection": '46275133' from E.OMOPSV
code "heparin sodium, porcine 4000 UNT/ML Injectable Solution": '43011972' from E.OMOPSV
code "heparin sodium, porcine 40000 UNT/ML Injectable Solution": '43011847' from E.OMOPSV
code "heparin sodium, porcine 50 UNT/ML Injection": '46275496' from E.OMOPSV
code "heparin sodium, porcine 5000 UNT/ML Cartridge": '46275506' from E.OMOPSV
code "heparin sodium, porcine 5000 UNT/ML Injectable Solution": '43011850' from E.OMOPSV
code "heparin sodium, porcine 5000 UNT/ML Injection": '46275508' from E.OMOPSV
code "heparin sodium, porcine 5000 UNT/ML Prefilled Syringe": '36249118' from E.OMOPSV
code "heparin sodium, porcine 6000 UNT/ML Injectable Solution": '43011973' from E.OMOPSV
code "heparin sodium, porcine 66 UNT/ML Injectable Solution": '43011974' from E.OMOPSV
code "heparin sodium, porcine 7500 UNT/ML Injectable Solution": '43011957' from E.OMOPSV
code "heparin sodium, porcine 8 UNT/ML Injectable Solution": '43011958' from E.OMOPSV
code "heparin sodium, porcine 8.3 UNT/ML Injectable Solution": '43011976' from E.OMOPSV
code "lepirudin 50 MG Injectable Solution": '36408950' from E.OMOPSV
code "lepirudin 50 MG Injectable Suspension": '44071379' from E.OMOPSV
code "lepirudin 50 MG Injection": '21112177' from E.OMOPSV
code "lepirudin 50 MG Prefilled Syringe": '36883971' from E.OMOPSV
code "lepirudin 50 MG/ML Injectable Solution": '19023526' from E.OMOPSV
code "nadroparin 19000 IU/ML Injection": '2917151' from E.OMOPSV
code "nadroparin 19000 UNT/ML Injectable Solution": '19001019' from E.OMOPSV
code "nadroparin 25000 UNT/ML Injectable Solution": '19001015' from E.OMOPSV
code "nadroparin 9500 IU/ML Injection": '2917158' from E.OMOPSV
code "nadroparin 9500 UNT/ML Injectable Solution": '19001016' from E.OMOPSV
code "parnaparin 100 UNT/ML Prefilled Syringe": '35145372' from E.OMOPSV
code "parnaparin 10600 UNT/ML Prefilled Syringe": '2046467' from E.OMOPSV
code "parnaparin 10700 UNT/ML Prefilled Syringe": '2046463' from E.OMOPSV
code "parnaparin 150 UNT/ML Prefilled Syringe": '35148230' from E.OMOPSV
code "parnaparin 200 UNT/ML Prefilled Syringe": '35162150' from E.OMOPSV
code "parnaparin 5000 UNT Injectable Solution": '35130087' from E.OMOPSV
code "phenindione 10 MG Oral Tablet": '19021888' from E.OMOPSV
code "phenindione 25 MG Oral Tablet": '19004009' from E.OMOPSV
code "phenindione 50 MG Oral Tablet": '19004010' from E.OMOPSV
code "phenprocoumon 1 MG/ML Oral Suspension": '1235796' from E.OMOPSV
code "phenprocoumon 3 MG Oral Tablet": '19079272' from E.OMOPSV
code "reviparin 17.2 UNT/ML Prefilled Syringe": '41240196' from E.OMOPSV
code "reviparin 1750 UNT Injectable Solution": '40990210' from E.OMOPSV
code "reviparin 5.72 UNT/ML Prefilled Syringe": '42717880' from E.OMOPSV
code "reviparin 5.73 UNT/ML Injectable Solution": '40958976' from E.OMOPSV
code "reviparin 5.73 UNT/ML Prefilled Syringe": '40822031' from E.OMOPSV
code "reviparin 5000 UNT Injectable Solution": '35137902' from E.OMOPSV
code "reviparin 55.2 MG/ML Prefilled Syringe": '2040356' from E.OMOPSV
code "reviparin 5728 UNT/ML Injectable Solution": '590446' from E.OMOPSV
code "reviparin 5728 UNT/ML Prefilled Syringe": '42902710' from E.OMOPSV
code "reviparin 5730 UNT/ML Injectable Solution": '36406720' from E.OMOPSV
code "reviparin 7 UNT/ML Injectable Solution": '40865509' from E.OMOPSV
code "reviparin 7 UNT/ML Prefilled Syringe": '41115223' from E.OMOPSV
code "reviparin 7000 UNT/ML Injectable Solution": '40834373' from E.OMOPSV
code "reviparin 7000 UNT/ML Prefilled Syringe": '41240195' from E.OMOPSV
code "reviparin 71.6 MG/ML Injectable Solution": '36889670' from E.OMOPSV
code "reviparin 71.7 MG/ML Injectable Solution": '42712526' from E.OMOPSV
code "reviparin 9.2 MG/ML Injectable Solution": '41271069' from E.OMOPSV
code "reviparin 9530 UNT/ML Prefilled Syringe": '42715121' from E.OMOPSV
code "reviparin 9540 UNT/ML Prefilled Syringe": '41271070' from E.OMOPSV
code "reviparin 97.6 MG/ML Injectable Solution": '36880950' from E.OMOPSV
code "reviparin 97.7 MG/ML Injectable Solution": '42713831' from E.OMOPSV
code "reviparin sodium 55.2 MG/ML Injectable Solution": '40163301' from E.OMOPSV
code "reviparin sodium 5730 UNT/ML Prefilled Syringe": '42902706' from E.OMOPSV
code "rivaroxaban 1 MG/ML Oral Suspension": '702551' from E.OMOPSV
code "rivaroxaban 10 MG Delayed Release Oral Tablet": '43137701' from E.OMOPSV
code "rivaroxaban 10 MG Oral Granules": '35130845' from E.OMOPSV
code "rivaroxaban 10 MG Oral Tablet": '40241333' from E.OMOPSV
code "rivaroxaban 103 MG Granules for Oral Suspension": '1831986' from E.OMOPSV
code "rivaroxaban 15 MG Delayed Release Oral Tablet": '43181738' from E.OMOPSV
code "rivaroxaban 15 MG Oral Granules": '35144287' from E.OMOPSV
code "rivaroxaban 15 MG Oral Tablet": '40244444' from E.OMOPSV
code "rivaroxaban 2.5 MG Oral Tablet": '35200878' from E.OMOPSV
code "rivaroxaban 20 MG Delayed Release Oral Tablet": '43137705' from E.OMOPSV
code "rivaroxaban 20 MG Oral Tablet": '40244448' from E.OMOPSV
code "rivaroxaban 35 MG Oral Tablet": '44122941' from E.OMOPSV
code "rivaroxaban 51.7 MG Granules for Oral Suspension": '1831981' from E.OMOPSV
code "sulodexide 250 UNT Oral Capsule": '42962443' from E.OMOPSV
code "tinzaparin 10 UNT/ML Injectable Solution": '41177276' from E.OMOPSV
code "tinzaparin 10 UNT/ML Prefilled Syringe": '41051948' from E.OMOPSV
code "tinzaparin 11700 UNT/ML Injectable Solution": '44109669' from E.OMOPSV
code "tinzaparin 120 MG/ML Injectable Solution": '19104480' from E.OMOPSV
code "tinzaparin 120 MG/ML Prefilled Syringe": '37593555' from E.OMOPSV
code "tinzaparin 141 MG/ML Injectable Solution": '19104227' from E.OMOPSV
code "tinzaparin 19.9 UNT/ML Injectable Solution": '40989786' from E.OMOPSV
code "tinzaparin 20 UNT/ML Injectable Solution": '41051949' from E.OMOPSV
code "tinzaparin 20 UNT/ML Prefilled Syringe": '41177277' from E.OMOPSV
code "tinzaparin 24.2 MG/ML Injectable Solution": '41083555' from E.OMOPSV
code "tinzaparin 241 MG/ML Injectable Solution": '36891669' from E.OMOPSV
code "tinzaparin 241 MG/ML Prefilled Syringe": '36419314' from E.OMOPSV
code "tinzaparin 268 MG/ML Prefilled Syringe": '40958512' from E.OMOPSV
code "tinzaparin 301 MG/ML Prefilled Syringe": '41083554' from E.OMOPSV
code "tinzaparin 344 MG/ML Prefilled Syringe": '40927263' from E.OMOPSV
code "tinzaparin 346 MG/ML Prefilled Syringe": '41239753' from E.OMOPSV
code "tinzaparin 402 MG/ML Prefilled Syringe": '41270606' from E.OMOPSV
code "tinzaparin 403 MG/ML Prefilled Syringe": '41020748' from E.OMOPSV
code "tinzaparin 482 MG/ML Prefilled Syringe": '41301680' from E.OMOPSV
code "tinzaparin 60.4 MG/ML Injectable Solution": '42715128' from E.OMOPSV
code "tinzaparin 60.5 MG/ML Injectable Solution": '41239754' from E.OMOPSV
code "tinzaparin 603 MG/ML Prefilled Syringe": '41114769' from E.OMOPSV
code "tinzaparin sodium 10000 UNT/ML Injectable Solution": '40180715' from E.OMOPSV
code "tinzaparin sodium 10000 UNT/ML Prefilled Syringe": '42902894' from E.OMOPSV
code "tinzaparin sodium 20000 UNT/ML Injectable Solution": '40180717' from E.OMOPSV
code "tinzaparin sodium 20000 UNT/ML Prefilled Syringe": '42902916' from E.OMOPSV
code "tioclomarol 4 MG Oral Tablet": '19107417' from E.OMOPSV
code "warfarin 0.002 MG/MG Oral Granules": '35831300' from E.OMOPSV
code "warfarin 5 MG/ML Injectable Solution": '1235144' from E.OMOPSV
code "warfarin sodium 0.5 MG Oral Tablet": '40163508' from E.OMOPSV
code "warfarin sodium 1 MG Oral Tablet": '40163510' from E.OMOPSV
code "warfarin sodium 10 MG Oral Tablet": '40163518' from E.OMOPSV
code "warfarin sodium 2 MG Oral Tablet": '40163524' from E.OMOPSV
code "warfarin sodium 2 MG/ML Injectable Solution": '40163530' from E.OMOPSV
code "warfarin sodium 2.5 MG Oral Tablet": '40163534' from E.OMOPSV
code "warfarin sodium 3 MG Oral Tablet": '40163540' from E.OMOPSV
code "warfarin sodium 4 MG Oral Tablet": '40163546' from E.OMOPSV
code "warfarin sodium 5 MG Oral Tablet": '40163554' from E.OMOPSV
code "warfarin sodium 6 MG Oral Tablet": '40163560' from E.OMOPSV
code "warfarin sodium 7.5 MG Oral Tablet": '40163566' from E.OMOPSV

concept "Anticoagulation Drugs": {
  "AMNIOTIC FLUID (BOVINE) 11 X / Bos taurus brain preparation 10 X / Bos taurus ovary preparation 11 X / Bos taurus placenta preparation 10 X / Bos taurus spleen preparation 11 X / Bos taurus testicle preparation 10 X / ... Delayed Release Oral Capsule",
  "Aesculus hippocastanum bark extract 0.05 MG/MG / heparin 0.05 UNT/MG / Thiamine 0.0025 MG/MG Topical Ointment",
  "Aesculus hippocastanum bark extract 0.0501 MG/MG / heparin 0.0501 UNT/MG / Thiamine 0.0025 MG/MG Topical Ointment",
  "Allantoin 0.0025 MG/MG / dexpanthenol 0.0025 MG/MG / heparin 0.12 UNT/MG / Oxyphenbutazone 0.03 MG/MG Topical Cream",
  "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.3 UNT/MG Topical Gel",
  "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.3 UNT/MG Topical Ointment",
  "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.5 UNT/MG Topical Ointment",
  "Allantoin 0.003 MG/MG / dexpanthenol 0.004 MG/MG / heparin 0.501 UNT/MG Topical Ointment",
  "Allantoin 0.003 MG/MG / dexpanthenol 0.05 MG/MG / heparin 0.1 UNT/MG / Hydrocortisone 0.0025 MG/MG / Procaine 0.002 MG/MG Topical Ointment",
  "Allantoin 0.008 MG/MG / heparin 0.03 UNT/MG / Hexachlorophene 0.02 MG/MG / Ichtyolammonium 0.025 MG/MG / Sulfur 0.1 MG/MG / Zinc Oxide 0.15 MG/MG Topical Cream",
  "Allantoin 0.01 MG/MG / Allium cepa whole extract 0.1 MG/MG / heparin 0.05 UNT/MG Topical Gel",
  "Allantoin 0.01 MG/MG / Allium cepa whole extract 0.1 MG/MG / heparin 0.0501 UNT/MG Topical Gel",
  "Allantoin 0.01 MG/MG / heparin 0.05 UNT/MG / Onion extract 0.1 MG/MG Vaginal Gel",
  "Allantoin 0.0333 MG/MG / Allium cepa whole extract 0.333 MG/MG / heparin 0.167 UNT/MG Topical Gel",
  "Allantoin 20 MG / Aluminum carbonate 12 MG / Bismuth 100 MG / dexpanthenol 100 MG / heparin 200 UNT / Hydrocortisone 5 MG / Procaine 4 MG Rectal Suppository",
  "Arnica extract 0.1 MG/MG / guaiazulene 0.00005 MG/MG / heparin 0.00004 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.00005 MG/MG Topical Gel",
  "Arnica extract 0.1 MG/MG / guaiazulene 0.00005 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.00005 MG/MG Topical Gel",
  "Arnica extract 0.1 MG/MG / guaiazulene 0.00005 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.00005 MG/MG Topical Ointment",
  "Arnica extract 0.1 MG/MG / guaiazulene 0.0000501 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.0000501 MG/MG Topical Gel",
  "Arnica extract 0.1 MG/MG / guaiazulene 0.0000501 MG/MG / heparin 0.04 UNT/MG / Lecithin 0.01 MG/MG / Matricaria chamomilla flowering top oil 0.0000501 MG/MG Topical Ointment",
  "Benzocaine 0.03 MG/MG / dexpanthenol 0.025 MG/MG / heparin 0.05 UNT/MG / Menthol 0.003 MG/MG / prednisolone 0.0005 MG/MG / Tyrothricin 0.001 MG/MG / Vitamin B 12 0.0001 MG/MG Topical Ointment",
  "Benzocaine 60 MG / dexpanthenol 50 MG / heparin 200 UNT / Menthol 0.05 MG / prednisolone 2 MG / Vitamin B 12 0.4 MG Rectal Suppository",
  "Benzocaine 900 MG / dexpanthenol 750 MG / heparin 2500 UNT / Menthol 30 MG / prednisolone 25 MG / Tyrothricin 10 MG / Vitamin B 12 5 MG Rectal Suppository",
  "Benzocaine 900 MG / dexpanthenol 750 MG / heparin 2500 UNT / Menthol 30 MG / prednisolone 70 MG / Tyrothricin 10 MG / Vitamin B 12 5 MG Rectal Suppository",
  "Certoparin",
  "Citric Acid 0.37 MG/ML / heparin 2 UNT/ML / Sodium Chloride 9 MG/ML / Sodium Phosphate, Dibasic 4.3 MG/ML Injection",
  "Citric Acid 1 MG/ML / Glucose 50 MG/ML / heparin 50 UNT/ML / Sodium Phosphate, Dibasic 4.1 MG/ML Injection",
  "Clorindione 2 MG Oral Tablet",
  "Dalteparin 10 UNT/ML Injectable Solution",
  "Dalteparin 100 MG/ML Injectable Solution",
  "Dalteparin 1000 UNT/ML Injectable Solution",
  "Dalteparin 1000 UNT/ML Prefilled Syringe",
  "Dalteparin 10000 UNT/ML Injection",
  "Dalteparin 12.5 UNT/ML Injectable Solution",
  "Dalteparin 12.5 UNT/ML Prefilled Syringe",
  "Dalteparin 12500 UNT/ML Injectable Solution",
  "Dalteparin 12500 UNT/ML Injection",
  "Dalteparin 12500000 UNT/ML Prefilled Syringe",
  "Dalteparin 2.5 UNT/ML Injectable Solution",
  "Dalteparin 2.5 UNT/ML Prefilled Syringe",
  "Dalteparin 226 MG/ML Injectable Solution",
  "Dalteparin 227 MG/ML Injectable Solution",
  "Dalteparin 228 MG/ML Injectable Solution",
  "Dalteparin 24 UNT/ML Prefilled Syringe",
  "Dalteparin 25 UNT/ML Injectable Solution",
  "Dalteparin 25 UNT/ML Prefilled Syringe",
  "Dalteparin 250 UNT/ML Prefilled Syringe",
  "Dalteparin 2500 UNT/ML Injection",
  "Dalteparin 2500 UNT/ML Prefilled Syringe",
  "Dalteparin 25000 UNT/ML Injection",
  "Dalteparin 36000 IU/ML Prefilled Syringe",
  "Dalteparin 5000 UNT Injectable Solution",
  "Dalteparin 5000 UNT/ML Prefilled Syringe",
  "Dalteparin 6250 UNT/ML Injectable Solution",
  "Dalteparin 900 MG/ML Injectable Solution",
  "Dexamethasone 0.0002 MG/MG / heparin 0.05 UNT/MG / Sodium Ichtosylate 0.06 MG/MG Topical Cream",
  "Diclofenac 0.00001 MG/MG / heparin 0.4 UNT/MG Transdermal System",
  "Diclofenac 0.01 MG/MG / heparin 0.4 UNT/MG Transdermal System",
  "Dihydroergotamine 0.5 MG / heparin 5000 UNT Prefilled Syringe",
  "Dihydroergotamine 0.714 MG/ML / heparin 7500 UNT/ML / Lidocaine 10 MG/ML Injectable Solution",
  "Dihydroergotamine 0.714 MG/ML / heparin 7500 UNT/ML Injectable Solution",
  "Dihydroergotamine 1 MG/ML / heparin 5000 UNT/ML / Lidocaine 10 MG/ML Injectable Solution",
  "Enoxaparin 1 UNT/ML Injectable Solution",
  "Enoxaparin 10 MG/ML Injectable Solution",
  "Enoxaparin 10 UNT/ML Injectable Solution",
  "Enoxaparin 10 UNT/ML Prefilled Syringe",
  "Enoxaparin 100 MG/ML Injection",
  "Enoxaparin 10000 UNT/ML Injectable Solution",
  "Enoxaparin 10000 UNT/ML Prefilled Syringe",
  "Enoxaparin 13.3 UNT/ML Prefilled Syringe",
  "Enoxaparin 133 MG/ML Prefilled Syringe",
  "Enoxaparin 15 UNT/ML Prefilled Syringe",
  "Enoxaparin 150 MG/ML Injectable Solution",
  "Enoxaparin 150 MG/ML Injection",
  "Enoxaparin 15000 UNT/ML Injectable Solution",
  "Enoxaparin 15000 UNT/ML Prefilled Syringe",
  "Enoxaparin 20 MG/ML Injectable Solution",
  "Enoxaparin 30 UNT/ML Prefilled Syringe",
  "Enoxaparin 33.3 MG/ML Injectable Solution",
  "Enoxaparin 5 UNT/ML Prefilled Syringe",
  "Enoxaparin 6 UNT/ML Prefilled Syringe",
  "Enoxaparin 7.5 UNT/ML Prefilled Syringe",
  "Escin 0.01 MG/MG / heparin 0.00005 UNT/MG / Salicylic Acid 0.05 MG/MG Topical Gel",
  "Escin 0.01 MG/MG / heparin 0.0000501 UNT/MG / Salicylic Acid 0.05 MG/MG Topical Gel",
  "Escin 0.02 MG/MG / heparin 0.0001 UNT/MG / Phospholipids 0.01 MG/MG Topical Gel",
  "Flufenamic Acid 0.035 MG/MG / heparin 0.1 UNT/MG / Niacin 0.0125 MG/MG / Salicylic Acid 0.05 MG/MG Topical Ointment",
  "Gentamicin 0.02 MG/ML / heparin 3500 UNT/ML / Vancomycin 0.1 MG/ML Injectable Solution",
  "Glucose 50 MG/ML / heparin 100 UNT/ML Injection",
  "Glucose 50 MG/ML / heparin 40 UNT/ML Injectable Solution",
  "Glucose 50 MG/ML / heparin 40 UNT/ML Injection",
  "Glucose 50 MG/ML / heparin 50 UNT/ML Injection",
  "Melagatran 10 MG/ML Prefilled Syringe",
  "Nadroparin 10 UNT/ML Prefilled Syringe",
  "Nadroparin 100 MG/ML Injectable Solution",
  "Nadroparin 11.4 UNT/ML Prefilled Syringe",
  "Nadroparin 19 UNT/ML Prefilled Syringe",
  "Nadroparin 190 MG/ML Injectable Solution",
  "Nadroparin 1900 UNT/ML Injectable Solution",
  "Nadroparin 19000 UNT/ML Injection",
  "Nadroparin 19000 UNT/ML Prefilled Syringe",
  "Nadroparin 25.3 UNT/ML Prefilled Syringe",
  "Nadroparin 633 UNT/ML Injectable Solution",
  "Nadroparin 8.6 UNT/ML Prefilled Syringe",
  "Nadroparin 9.5 UNT/ML Injectable Solution",
  "Nadroparin 9.5 UNT/ML Prefilled Syringe",
  "Nadroparin 9.53 UNT/ML Injectable Solution",
  "Nadroparin 9500 UNT/ML Injection",
  "Nadroparin 9500 UNT/ML Prefilled Syringe",
  "Phenprocoumon 1.5 MG Oral Tablet",
  "Phenprocoumon 10 MG/ML Injectable Solution",
  "Warfarin 0.02 MG/ML Oral Solution",
  "Warfarin 0.1 MG/ML Oral Solution",
  "Warfarin 0.2 MG/ML Oral Solution",
  "Warfarin 0.2 MG/ML Oral Suspension",
  "Warfarin 0.3 MG/ML Oral Solution",
  "Warfarin 0.4 MG/ML Oral Solution",
  "Warfarin 0.4 MG/ML Oral Suspension",
  "Warfarin 0.5 MG/ML Oral Solution",
  "Warfarin 0.6 MG/ML Oral Solution",
  "Warfarin 0.6 MG/ML Oral Suspension",
  "Warfarin 0.8 MG/ML Oral Solution",
  "Warfarin 0.832 MG/ML Oral Solution",
  "Warfarin 1 MG Oral Capsule",
  "Warfarin 1 MG/ML Oral Solution",
  "Warfarin 1 MG/ML Oral Suspension",
  "Warfarin 2 MG/ML Oral Granules",
  "Warfarin 2 MG/ML Oral Solution",
  "Warfarin 2 MG/ML Oral Suspension",
  "Warfarin 3 MG Oral Capsule",
  "Warfarin 5 MG Injectable Suspension",
  "Warfarin 5 MG Oral Capsule",
  "Warfarin 5 MG/ML Oral Solution",
  "Ximelagatran 24 MG Oral Tablet",
  "acenocoumarol 1 MG Oral Tablet",
  "acenocoumarol 4 MG Oral Tablet",
  "alpha Tocopherol 3 MG / Desonide 0.5 MG / heparin 500 UNT / Lidocaine 10 MG / Ruscosides 20 MG / Vitamin A 5000 UNT Rectal Suppository",
  "apixaban 2.5 MG Delayed Release Oral Tablet",
  "apixaban 2.5 MG Oral Tablet",
  "apixaban 5 MG Delayed Release Oral Tablet",
  "apixaban 5 MG Oral Tablet",
  "argatroban 0.5 MG/ML Injectable Solution",
  "argatroban 0.5 MG/ML Prefilled Syringe",
  "argatroban 1 MG/ML Injectable Solution",
  "argatroban 1 MG/ML Injection",
  "argatroban 100 MG/ML Injectable Solution",
  "argatroban 100 MG/ML Injection",
  "argatroban 100 MG/ML Prefilled Syringe",
  "argatroban 40 MG/ML Injectable Solution",
  "argatroban 5 MG/ML Injectable Solution",
  "bemiparin 125 MG/ML Prefilled Syringe",
  "bemiparin 12500 UNT/ML Injectable Solution",
  "bemiparin 175 MG/ML Prefilled Syringe",
  "bemiparin 17500 UNT/ML Injectable Solution",
  "bemiparin 25000 UNT/ML Injectable Solution",
  "bemiparin sodium 12500 UNT/ML Prefilled Syringe",
  "bemiparin sodium 17500 UNT/ML Prefilled Syringe",
  "bemiparin sodium 22500 UNT/ML Prefilled Syringe",
  "bemiparin sodium 25000 UNT/ML Prefilled Syringe",
  "bemiparin sodium 40000 UNT/ML Prefilled Syringe",
  "betrixaban 40 MG Oral Capsule",
  "betrixaban 80 MG Oral Capsule",
  "bisabolol 0.003 MG/MG / heparin 0.0002 UNT/MG Topical Cream",
  "bisabolol 0.003 MG/MG / heparin 0.0002 UNT/MG Topical Ointment",
  "bivalirudin 100 MG Injection",
  "bivalirudin 25 MG/ML Injectable Solution",
  "bivalirudin 250 MG Injectable Solution",
  "bivalirudin 250 MG Injectable Suspension",
  "bivalirudin 250 MG Injection",
  "bivalirudin 250 MG Prefilled Syringe",
  "bivalirudin 5 MG/ML Injection",
  "dabigatran etexilate 110 MG Oral Capsule",
  "dabigatran etexilate 110 MG Oral Pellet",
  "dabigatran etexilate 150 MG Oral Capsule",
  "dabigatran etexilate 150 MG Oral Pellet",
  "dabigatran etexilate 20 MG Oral Pellet",
  "dabigatran etexilate 30 MG Oral Pellet",
  "dabigatran etexilate 40 MG Oral Pellet",
  "dabigatran etexilate 50 MG Oral Pellet",
  "dabigatran etexilate 75 MG Oral Capsule",
  "dalteparin 10000 IU/ML Injectable Solution",
  "dalteparin 10000 IU/ML Injection",
  "dalteparin 12500 IU/ML Injectable Solution",
  "dalteparin 12500 IU/ML Injection",
  "dalteparin 12500 IU/ML Prefilled Syringe",
  "dalteparin 2500 IU/ML Injectable Solution",
  "dalteparin 25000 IU/ML Injectable Solution",
  "dalteparin 25000 IU/ML Injection",
  "dalteparin 25000 IU/ML Prefilled Syringe",
  "dalteparin 55.2 MG/ML Injectable Solution",
  "dalteparin 75 MG/ML Injectable Solution",
  "dalteparin sodium 10000 UNT/ML Injectable Solution",
  "dalteparin sodium 10000 UNT/ML Prefilled Syringe",
  "dalteparin sodium 12500 UNT/ML Prefilled Syringe",
  "dalteparin sodium 2500 UNT/ML Injectable Solution",
  "dalteparin sodium 2500 UNT/ML Injection",
  "dalteparin sodium 25000 UNT/ML Injectable Solution",
  "dalteparin sodium 25000 UNT/ML Prefilled Syringe",
  "dalteparin sodium 36 MG/ML / dihydroergotamine mesylate 1 MG/ML Injectable Solution",
  "dalteparin sodium 36 MG/ML Injectable Solution",
  "danaparoid 1250 IU/ML Injection",
  "danaparoid 1250 UNT/ML Injectable Solution",
  "danaparoid 1250 UNT/ML Injection",
  "danaparoid 1250 UNT/ML Prefilled Syringe",
  "desirudin 15 MG Injectable Solution",
  "desirudin 15 MG Injection",
  "dexpanthenol 0.025 MG/MG / Dimethyl Sulfoxide 0.15 MG/MG / heparin 0.0005 UNT/MG Topical Gel",
  "dexpanthenol 0.025 MG/MG / Dimethyl Sulfoxide 0.15 MG/MG / heparin 0.0005 UNT/MG Urethral Suppository",
  "dexpanthenol 0.025 MG/MG / Dimethyl Sulfoxide 0.15 MG/MG / heparin 0.000501 UNT/MG Topical Gel",
  "dicumarol 100 MG Oral Tablet",
  "dicumarol 25 MG Oral Capsule",
  "dicumarol 25 MG Oral Tablet",
  "dicumarol 50 MG Oral Capsule",
  "dicumarol 50 MG Oral Tablet",
  "edoxaban 15 MG Delayed Release Oral Tablet",
  "edoxaban 15 MG Disintegrating Oral Tablet",
  "edoxaban 30 MG Delayed Release Oral Tablet",
  "edoxaban 30 MG Disintegrating Oral Tablet",
  "edoxaban 60 MG Delayed Release Oral Tablet",
  "edoxaban 60 MG Disintegrating Oral Tablet",
  "enoxaparin 10000 IU/ML Injectable Solution",
  "enoxaparin 60 MG/ML Injectable Solution",
  "enoxaparin sodium 100 MG/ML Injectable Solution",
  "enoxaparin sodium 100 MG/ML Prefilled Syringe",
  "enoxaparin sodium 150 MG/ML Prefilled Syringe",
  "ethylene glycol 0.05 MG/MG / heparin 0.0005 UNT/MG Topical Gel",
  "ethylene glycol 0.0501 MG/MG / heparin 0.000501 UNT/MG Topical Gel",
  "factor IX 30 UNT/ML / factor VII 24 UNT/ML / factor X 30 UNT/ML / heparin 12.5 UNT/ML / Prothrombin 30 UNT/ML Injectable Solution",
  "factor IX 600 UNT / factor VII 500 UNT / factor X 600 UNT / heparin 250 UNT / Prothrombin 600 UNT Injectable Solution",
  "fluindione 20 MG Extended Release Oral Tablet",
  "fluindione 20 MG Oral Tablet",
  "fondaparinux 12.5 MG/ML Injectable Solution",
  "fondaparinux 12.5 MG/ML Injection",
  "fondaparinux 5 MG/ML Injectable Solution",
  "fondaparinux 5 MG/ML Injection",
  "fondaparinux sodium 12.5 MG/ML Prefilled Syringe",
  "fondaparinux sodium 5 MG/ML Prefilled Syringe",
  "glycol salicylate 0.05 MG/MG / heparin 0.5 UNT/MG / LEVOMENTHOL 0.005 MG/MG Vaginal Gel",
  "glycol salicylate 0.05 MG/MG / heparin 0.5 UNT/MG Vaginal Gel",
  "heparin 0.00005 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel",
  "heparin 0.00005 UNT/MG / polidocanol 0.03 MG/MG Topical Gel",
  "heparin 0.00005 UNT/MG Topical Gel",
  "heparin 0.00005 UNT/MG Topical Ointment",
  "heparin 0.0000501 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel",
  "heparin 0.0000501 UNT/MG / polidocanol 0.03 MG/MG Topical Gel",
  "heparin 0.0000501 UNT/MG Topical Gel",
  "heparin 0.00015 UNT/MG Topical Gel",
  "heparin 0.000167 UNT/MG / LEVOMENTHOL 0.0017 MG/MG / Salicylic Acid 0.017 MG/MG Topical Gel",
  "heparin 0.0003 UNT/MG Topical Cream",
  "heparin 0.0003 UNT/MG Topical Gel",
  "heparin 0.0003 UNT/MG Topical Ointment",
  "heparin 0.0004 UNT/MG Topical Gel",
  "heparin 0.0004 UNT/MG Topical Ointment",
  "heparin 0.0005 UNT/MG / LEVOMENTHOL 0.00002 MG/MG / Salicylic Acid 0.001 MG/MG Topical Gel",
  "heparin 0.0005 UNT/MG / LEVOMENTHOL 0.005 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel",
  "heparin 0.0005 UNT/MG Topical Gel",
  "heparin 0.0005 UNT/MG Topical Ointment",
  "heparin 0.000501 UNT/MG / LEVOMENTHOL 0.00002 MG/MG / Salicylic Acid 0.001 MG/MG Topical Gel",
  "heparin 0.000501 UNT/MG / LEVOMENTHOL 0.00501 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel",
  "heparin 0.000501 UNT/MG Topical Gel",
  "heparin 0.000501 UNT/MG Topical Ointment",
  "heparin 0.00056 UNT/MG Topical Gel",
  "heparin 0.00056 UNT/MG Topical Ointment",
  "heparin 0.0006 UNT/MG Topical Cream",
  "heparin 0.0006 UNT/MG Topical Gel",
  "heparin 0.0006 UNT/MG Topical Ointment",
  "heparin 0.001 MG/MG / Zinc Sulfate 0.005 MG/MG Vaginal Gel",
  "heparin 0.001 MG/MG Vaginal Gel",
  "heparin 0.001 UNT/MG Topical Gel",
  "heparin 0.001 UNT/MG Topical Ointment",
  "heparin 0.0015 UNT/MG Topical Gel",
  "heparin 0.0015 UNT/MG Topical Ointment",
  "heparin 0.00151 UNT/MG Topical Gel",
  "heparin 0.0018 UNT/MG Topical Gel",
  "heparin 0.0018 UNT/MG Topical Ointment",
  "heparin 0.002 UNT/ML / Sodium Chloride 0.009 MG/ML Injection",
  "heparin 0.003 UNT/MG Topical Gel",
  "heparin 0.003 UNT/MG Topical Ointment",
  "heparin 0.00313 MG/MG Vaginal Gel",
  "heparin 0.00417 MG/MG Vaginal Gel",
  "heparin 0.00418 MG/MG Vaginal Gel",
  "heparin 0.005 UNT/MG / Salicylic Acid 0.02 MG/MG Topical Ointment",
  "heparin 0.005 UNT/MG Topical Gel",
  "heparin 0.005 UNT/MG Topical Ointment",
  "heparin 0.00501 UNT/MG / Salicylic Acid 0.02 MG/MG Topical Ointment",
  "heparin 0.00501 UNT/MG Topical Gel",
  "heparin 0.00501 UNT/MG Topical Ointment",
  "heparin 0.00543 MG/MG Vaginal Gel",
  "heparin 0.00544 MG/MG Vaginal Gel",
  "heparin 0.006 UNT/MG Topical Gel",
  "heparin 0.006 UNT/MG Topical Ointment",
  "heparin 0.0075 UNT/MG Topical Gel",
  "heparin 0.0075 UNT/MG Topical Ointment",
  "heparin 0.01 UNT/MG Topical Gel",
  "heparin 0.01 UNT/MG Topical Ointment",
  "heparin 0.012 MG/MG Vaginal Gel",
  "heparin 0.012 UNT/MG Topical Gel",
  "heparin 0.015 UNT/MG Topical Gel",
  "heparin 0.015 UNT/MG Topical Ointment",
  "heparin 0.018 UNT/MG Topical Gel",
  "heparin 0.018 UNT/MG Topical Ointment",
  "heparin 0.025 UNT/MG Topical Gel",
  "heparin 0.025 UNT/MG Topical Ointment",
  "heparin 0.03 UNT/MG Topical Gel",
  "heparin 0.03 UNT/MG Topical Ointment",
  "heparin 0.045 UNT/MG Topical Gel",
  "heparin 0.045 UNT/MG Topical Ointment",
  "heparin 0.05 UNT/MG / Hydrocortisone 0.0033 MG/MG / polidocanol 0.03 MG/MG / Thiamine 0.001 MG/MG / Tyrothricin 0.001 MG/MG / Vitamin A 0.33 UNT/MG / Vitamin E 0.001 MG/MG Topical Ointment",
  "heparin 0.05 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel",
  "heparin 0.05 UNT/MG / Melilotus extract 0.001 MG/MG Topical Cream",
  "heparin 0.05 UNT/MG / Menthol 0.02 MG/MG / Pinus sylvestris bark extract 0.024 MG/MG Topical Ointment",
  "heparin 0.05 UNT/MG Topical Ointment",
  "heparin 0.0501 UNT/MG / Hydrocortisone 0.0033 MG/MG / polidocanol 0.03 MG/MG / Thiamine 0.001 MG/MG / Tyrothricin 0.001 MG/MG / Vitamin A 0.33 UNT/MG / Vitamin E 0.001 MG/MG Topical Ointment",
  "heparin 0.0501 UNT/MG / LEVOMENTHOL 0.002 MG/MG / Salicylic Acid 0.1 MG/MG Topical Gel",
  "heparin 0.0501 UNT/MG / Menthol 0.02 MG/MG / Pinus sylvestris bark extract 0.024 MG/MG Topical Ointment",
  "heparin 0.0501 UNT/MG Topical Ointment",
  "heparin 0.06 UNT/MG Topical Gel",
  "heparin 0.06 UNT/MG Topical Ointment",
  "heparin 0.065 UNT/MG / polidocanol 0.03 MG/MG / prednisolone 0.00223 MG/MG Topical Ointment",
  "heparin 0.125 UNT/MG Topical Ointment",
  "heparin 0.15 UNT/MG Topical Gel",
  "heparin 0.15 UNT/MG Topical Ointment",
  "heparin 0.151 UNT/MG Topical Gel",
  "heparin 0.175 UNT/MG / Zinc Oxide 0.005 MG/MG Topical Gel",
  "heparin 0.175 UNT/MG / Zinc Sulfate 0.005 MG/MG Topical Gel",
  "heparin 0.2 UNT/MG / LEVOMENTHOL 0.003 MG/MG Topical Cream",
  "heparin 0.2 UNT/MG Topical Cream",
  "heparin 0.2 UNT/MG Topical Gel",
  "heparin 0.2 UNT/MG Topical Ointment",
  "heparin 0.25 UNT/MG Topical Gel",
  "heparin 0.25 UNT/MG Topical Ointment",
  "heparin 0.3 UNT/MG / troxerutin 0.02 MG/MG Topical Ointment",
  "heparin 0.3 UNT/MG Topical Cream",
  "heparin 0.3 UNT/MG Topical Gel",
  "heparin 0.3 UNT/MG Topical Ointment",
  "heparin 0.3 UNT/MG Vaginal Gel",
  "heparin 0.4 UNT/MG Topical Cream",
  "heparin 0.4 UNT/MG Topical Gel",
  "heparin 0.4 UNT/MG Topical Ointment",
  "heparin 0.5 UNT/MG / Menthol 0.005 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel",
  "heparin 0.5 UNT/MG Topical Gel",
  "heparin 0.5 UNT/MG Topical Ointment",
  "heparin 0.5 UNT/MG Vaginal Gel",
  "heparin 0.501 UNT/MG / Menthol 0.005 MG/MG / Salicylic Acid 0.05 MG/MG Topical Gel",
  "heparin 0.501 UNT/MG Topical Gel",
  "heparin 0.501 UNT/MG Topical Ointment",
  "heparin 0.6 UNT/MG Topical Cream",
  "heparin 0.6 UNT/MG Topical Gel",
  "heparin 0.6 UNT/MG Topical Ointment",
  "heparin 0.6 UNT/MG Vaginal Gel",
  "heparin 0.65 UNT/ML Prefilled Applicator",
  "heparin 0.75 UNT/MG Topical Gel",
  "heparin 0.75 UNT/MG Topical Ointment",
  "heparin 0.8 UNT/MG Topical Ointment",
  "heparin 0.9 UNT/MG Topical Gel",
  "heparin 1 UNT/ML Injectable Solution",
  "heparin 1 UNT/ML Injection",
  "heparin 1.2 UNT/MG Stick",
  "heparin 1.2 UNT/MG Topical Cream",
  "heparin 1.2 UNT/MG Topical Gel",
  "heparin 1.2 UNT/MG Topical Ointment",
  "heparin 1.3 UNT/MG Ophthalmic Ointment",
  "heparin 1.5 UNT/MG Topical Cream",
  "heparin 1.5 UNT/MG Topical Gel",
  "heparin 1.5 UNT/MG Topical Ointment",
  "heparin 1.5 UNT/MG Vaginal Gel",
  "heparin 1.51 UNT/MG Vaginal Gel",
  "heparin 1.8 UNT/MG Topical Gel",
  "heparin 1.8 UNT/MG Topical Ointment",
  "heparin 1.8 UNT/MG Vaginal Gel",
  "heparin 10 UNT/ML Intraperitoneal Solution",
  "heparin 100 UNT/ML Irrigation Solution",
  "heparin 1000 IU/ML Injectable Solution",
  "heparin 1000 UNT/ML Topical Gel",
  "heparin 1000 UNT/ML Topical Ointment",
  "heparin 1000 UNT/ML Vaginal Gel",
  "heparin 10000 UNT Injectable Solution",
  "heparin 10000 UNT Topical Ointment",
  "heparin 10000 UNT/ML Prefilled Syringe",
  "heparin 100000 UNT Injectable Solution",
  "heparin 10300 IU/ML Injectable Solution",
  "heparin 114 UNT/ML Topical Gel",
  "heparin 120 UNT / polidocanol 30 MG / prednisolone 1.68 MG Rectal Suppository",
  "heparin 125000 UNT/ML Prefilled Syringe",
  "heparin 1300 UNT/ML Prefilled Applicator",
  "heparin 15 UNT/ML Injectable Solution",
  "heparin 15 UNT/ML Prefilled Syringe",
  "heparin 150 UNT/ML Injectable Solution",
  "heparin 150 UNT/ML Prefilled Syringe",
  "heparin 15000 UNT/ML Prefilled Syringe",
  "heparin 16700 UNT/ML Prefilled Syringe",
  "heparin 171 UNT/ML Topical Gel",
  "heparin 180000 UNT/ML Topical Gel",
  "heparin 2 IU/ML Injectable Solution",
  "heparin 2 UNT/ML / Sodium Chloride 9 MG/ML Injection",
  "heparin 2.4 UNT/MG Topical Cream",
  "heparin 2.4 UNT/MG Topical Gel",
  "heparin 2.4 UNT/MG Topical Ointment",
  "heparin 20 UNT/ML Injectable Solution",
  "heparin 200 UNT/ML Injectable Solution",
  "heparin 200 UNT/ML Prefilled Syringe",
  "heparin 2000 UNT/ML Injectable Solution",
  "heparin 20000 UNT Injectable Solution",
  "heparin 20000 UNT Topical Ointment",
  "heparin 20000 UNT/ML Prefilled Syringe",
  "heparin 25 UNT/ML Injectable Solution",
  "heparin 25 UNT/ML Prefilled Syringe",
  "heparin 250 UNT/ML Prefilled Syringe",
  "heparin 2500 UNT / polidocanol 900 MG / prednisolone 61.4 MG Rectal Suppository",
  "heparin 2500 UNT/ML Injectable Solution",
  "heparin 25000 UNT Injectable Solution",
  "heparin 25000 UNT/ML Injection",
  "heparin 250000 UNT Injectable Solution",
  "heparin 3 IU/MG Topical Gel",
  "heparin 30000 UNT Topical Gel",
  "heparin 31300 UNT/ML Injectable Solution",
  "heparin 350 UNT/ML Prefilled Syringe",
  "heparin 3500 IU Topical Gel",
  "heparin 5 UNT/ML Injectable Solution",
  "heparin 50 UNT/ML Vaginal Gel",
  "heparin 500 UNT/ML Injectable Solution",
  "heparin 500 UNT/ML Injection",
  "heparin 500 UNT/ML Prefilled Syringe",
  "heparin 5000 IU/ML Injectable Solution",
  "heparin 5000 UNT Injectable Solution",
  "heparin 5000 UNT Prefilled Syringe",
  "heparin 5000 UNT Topical Ointment",
  "heparin 5000 UNT/ML Ophthalmic Solution",
  "heparin 50000 UNT/ML Injectable Solution",
  "heparin 50000 UNT/ML Topical Gel",
  "heparin 5000000 UNT/ML Injectable Solution",
  "heparin 521 UNT/ML Injectable Solution",
  "heparin 521 UNT/ML Injection",
  "heparin 60 UNT/MG Topical Gel",
  "heparin 60000 UNT/ML Topical Gel",
  "heparin 60000 UNT/ML Topical Ointment",
  "heparin 650 UNT/ML Prefilled Applicator",
  "heparin 7000 UNT Topical Ointment",
  "heparin 750 UNT/ML Injectable Solution",
  "heparin 7500 UNT Prefilled Syringe",
  "heparin 80000 UNT/ML Prefilled Syringe",
  "heparin 83300 UNT/ML Prefilled Syringe",
  "heparin calcium 25000 UNT/ML Injectable Solution",
  "heparin calcium 25000 UNT/ML Prefilled Syringe",
  "heparin sodium, bovine 1000 UNT/ML Injectable Solution",
  "heparin sodium, bovine 10000 UNT/ML Injectable Solution",
  "heparin sodium, bovine 5000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 0.25 UNT/ML Injectable Solution",
  "heparin sodium, porcine 1 UNT/ML Prefilled Syringe",
  "heparin sodium, porcine 10 UNT/ML Injectable Solution",
  "heparin sodium, porcine 10 UNT/ML Injection",
  "heparin sodium, porcine 10 UNT/ML Prefilled Syringe",
  "heparin sodium, porcine 100 UNT/ML Injectable Solution",
  "heparin sodium, porcine 100 UNT/ML Injection",
  "heparin sodium, porcine 100 UNT/ML Prefilled Syringe",
  "heparin sodium, porcine 1000 UNT/ML / taurolidine 13.5 MG/ML Injection",
  "heparin sodium, porcine 1000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 1000 UNT/ML Injection",
  "heparin sodium, porcine 1000 UNT/ML Prefilled Syringe",
  "heparin sodium, porcine 10000 UNT/ML Cartridge",
  "heparin sodium, porcine 10000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 10000 UNT/ML Injection",
  "heparin sodium, porcine 10000 UNT/ML Prefilled Syringe",
  "heparin sodium, porcine 12500 UNT/ML Injectable Solution",
  "heparin sodium, porcine 15000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 2 UNT/ML Injectable Solution",
  "heparin sodium, porcine 2 UNT/ML Injection",
  "heparin sodium, porcine 2.5 UNT/ML Injectable Solution",
  "heparin sodium, porcine 2000 UNT/ML Injection",
  "heparin sodium, porcine 2000 UNT/ML Prefilled Syringe",
  "heparin sodium, porcine 20000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 250 UNT/ML Injectable Solution",
  "heparin sodium, porcine 2500 UNT/ML Injection",
  "heparin sodium, porcine 25000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 3000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 40 UNT/ML Injection",
  "heparin sodium, porcine 4000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 40000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 50 UNT/ML Injection",
  "heparin sodium, porcine 5000 UNT/ML Cartridge",
  "heparin sodium, porcine 5000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 5000 UNT/ML Injection",
  "heparin sodium, porcine 5000 UNT/ML Prefilled Syringe",
  "heparin sodium, porcine 6000 UNT/ML Injectable Solution",
  "heparin sodium, porcine 66 UNT/ML Injectable Solution",
  "heparin sodium, porcine 7500 UNT/ML Injectable Solution",
  "heparin sodium, porcine 8 UNT/ML Injectable Solution",
  "heparin sodium, porcine 8.3 UNT/ML Injectable Solution",
  "lepirudin 50 MG Injectable Solution",
  "lepirudin 50 MG Injectable Suspension",
  "lepirudin 50 MG Injection",
  "lepirudin 50 MG Prefilled Syringe",
  "lepirudin 50 MG/ML Injectable Solution",
  "nadroparin 19000 IU/ML Injection",
  "nadroparin 19000 UNT/ML Injectable Solution",
  "nadroparin 25000 UNT/ML Injectable Solution",
  "nadroparin 9500 IU/ML Injection",
  "nadroparin 9500 UNT/ML Injectable Solution",
  "parnaparin 100 UNT/ML Prefilled Syringe",
  "parnaparin 10600 UNT/ML Prefilled Syringe",
  "parnaparin 10700 UNT/ML Prefilled Syringe",
  "parnaparin 150 UNT/ML Prefilled Syringe",
  "parnaparin 200 UNT/ML Prefilled Syringe",
  "parnaparin 5000 UNT Injectable Solution",
  "phenindione 10 MG Oral Tablet",
  "phenindione 25 MG Oral Tablet",
  "phenindione 50 MG Oral Tablet",
  "phenprocoumon 1 MG/ML Oral Suspension",
  "phenprocoumon 3 MG Oral Tablet",
  "reviparin 17.2 UNT/ML Prefilled Syringe",
  "reviparin 1750 UNT Injectable Solution",
  "reviparin 5.72 UNT/ML Prefilled Syringe",
  "reviparin 5.73 UNT/ML Injectable Solution",
  "reviparin 5.73 UNT/ML Prefilled Syringe",
  "reviparin 5000 UNT Injectable Solution",
  "reviparin 55.2 MG/ML Prefilled Syringe",
  "reviparin 5728 UNT/ML Injectable Solution",
  "reviparin 5728 UNT/ML Prefilled Syringe",
  "reviparin 5730 UNT/ML Injectable Solution",
  "reviparin 7 UNT/ML Injectable Solution",
  "reviparin 7 UNT/ML Prefilled Syringe",
  "reviparin 7000 UNT/ML Injectable Solution",
  "reviparin 7000 UNT/ML Prefilled Syringe",
  "reviparin 71.6 MG/ML Injectable Solution",
  "reviparin 71.7 MG/ML Injectable Solution",
  "reviparin 9.2 MG/ML Injectable Solution",
  "reviparin 9530 UNT/ML Prefilled Syringe",
  "reviparin 9540 UNT/ML Prefilled Syringe",
  "reviparin 97.6 MG/ML Injectable Solution",
  "reviparin 97.7 MG/ML Injectable Solution",
  "reviparin sodium 55.2 MG/ML Injectable Solution",
  "reviparin sodium 5730 UNT/ML Prefilled Syringe",
  "rivaroxaban 1 MG/ML Oral Suspension",
  "rivaroxaban 10 MG Delayed Release Oral Tablet",
  "rivaroxaban 10 MG Oral Granules",
  "rivaroxaban 10 MG Oral Tablet",
  "rivaroxaban 103 MG Granules for Oral Suspension",
  "rivaroxaban 15 MG Delayed Release Oral Tablet",
  "rivaroxaban 15 MG Oral Granules",
  "rivaroxaban 15 MG Oral Tablet",
  "rivaroxaban 2.5 MG Oral Tablet",
  "rivaroxaban 20 MG Delayed Release Oral Tablet",
  "rivaroxaban 20 MG Oral Tablet",
  "rivaroxaban 35 MG Oral Tablet",
  "rivaroxaban 51.7 MG Granules for Oral Suspension",
  "sulodexide 250 UNT Oral Capsule",
  "tinzaparin 10 UNT/ML Injectable Solution",
  "tinzaparin 10 UNT/ML Prefilled Syringe",
  "tinzaparin 11700 UNT/ML Injectable Solution",
  "tinzaparin 120 MG/ML Injectable Solution",
  "tinzaparin 120 MG/ML Prefilled Syringe",
  "tinzaparin 141 MG/ML Injectable Solution",
  "tinzaparin 19.9 UNT/ML Injectable Solution",
  "tinzaparin 20 UNT/ML Injectable Solution",
  "tinzaparin 20 UNT/ML Prefilled Syringe",
  "tinzaparin 24.2 MG/ML Injectable Solution",
  "tinzaparin 241 MG/ML Injectable Solution",
  "tinzaparin 241 MG/ML Prefilled Syringe",
  "tinzaparin 268 MG/ML Prefilled Syringe",
  "tinzaparin 301 MG/ML Prefilled Syringe",
  "tinzaparin 344 MG/ML Prefilled Syringe",
  "tinzaparin 346 MG/ML Prefilled Syringe",
  "tinzaparin 402 MG/ML Prefilled Syringe",
  "tinzaparin 403 MG/ML Prefilled Syringe",
  "tinzaparin 482 MG/ML Prefilled Syringe",
  "tinzaparin 60.4 MG/ML Injectable Solution",
  "tinzaparin 60.5 MG/ML Injectable Solution",
  "tinzaparin 603 MG/ML Prefilled Syringe",
  "tinzaparin sodium 10000 UNT/ML Injectable Solution",
  "tinzaparin sodium 10000 UNT/ML Prefilled Syringe",
  "tinzaparin sodium 20000 UNT/ML Injectable Solution",
  "tinzaparin sodium 20000 UNT/ML Prefilled Syringe",
  "tioclomarol 4 MG Oral Tablet",
  "warfarin 0.002 MG/MG Oral Granules",
  "warfarin 5 MG/ML Injectable Solution",
  "warfarin sodium 0.5 MG Oral Tablet",
  "warfarin sodium 1 MG Oral Tablet",
  "warfarin sodium 10 MG Oral Tablet",
  "warfarin sodium 2 MG Oral Tablet",
  "warfarin sodium 2 MG/ML Injectable Solution",
  "warfarin sodium 2.5 MG Oral Tablet",
  "warfarin sodium 3 MG Oral Tablet",
  "warfarin sodium 4 MG Oral Tablet",
  "warfarin sodium 5 MG Oral Tablet",
  "warfarin sodium 6 MG Oral Tablet",
  "warfarin sodium 7.5 MG Oral Tablet"
}
