// This file has been generated automatically from
// commit edaaf809a126b08f1c96ffd983434cb73973fa4f or https://github.com/indicate-eu/data-dictionary
// Concept set(s)
// * Acenocoumarol (1 direct entries) [modified 2026-04-09]
// * Apixaban (1 direct entries) [modified 2026-04-09]
// * Argatroban (1 direct entries) [modified 2026-04-09]
// * Bemiparin (1 direct entries) [modified 2026-04-09]
// * Betrixaban (1 direct entries) [modified 2026-04-09]
// * Bivalirudin (1 direct entries) [modified 2026-04-09]
// * Certoparin (1 direct entries) [modified 2026-04-09]
// * Clorindione (1 direct entries) [modified 2026-04-09]
// * Dabigatran Etexilate (1 direct entries) [modified 2026-04-09]
// * Dalteparin (1 direct entries) [modified 2026-04-09]
// * Danaparoid (1 direct entries) [modified 2026-04-09]
// * Desirudin (1 direct entries) [modified 2026-04-09]
// * Dicumarol (1 direct entries) [modified 2026-04-09]
// * Edoxaban (1 direct entries) [modified 2026-04-09]
// * Enoxaparin (1 direct entries) [modified 2026-04-09]
// * Fluindione (1 direct entries) [modified 2026-04-09]
// * Fondaparinux (1 direct entries) [modified 2026-04-09]
// * Heparin (1 direct entries) [modified 2026-04-09]
// * Lepirudin (1 direct entries) [modified 2026-04-09]
// * Melagatran (1 direct entries) [modified 2026-04-09]
// * Nadroparin (1 direct entries) [modified 2026-04-09]
// * Parnaparin (1 direct entries) [modified 2026-04-09]
// * Phenindione (1 direct entries) [modified 2026-04-09]
// * Phenprocoumon (1 direct entries) [modified 2026-04-09]
// * Reviparin (1 direct entries) [modified 2026-04-09]
// * Rivaroxaban (1 direct entries) [modified 2026-04-09]
// * Sulodexide (1 direct entries) [modified 2026-04-09]
// * Tinzaparin (1 direct entries) [modified 2026-04-09]
// * Tioclomarol (1 direct entries) [modified 2026-04-09]
// * Warfarin (1 direct entries) [modified 2026-04-09]
// * Ximelagatran (1 direct entries) [modified 2026-04-09]

// Do not edit

library "AnticoagulationDrugs"

include IndicateQiElements called E

code "acenocoumarol": '19024063' from E."OMOPSV Hierarchy"
code "apixaban": '43013024' from E."OMOPSV Hierarchy"
code "argatroban": '1322207' from E."OMOPSV Hierarchy"
code "bemiparin": '19069137' from E."OMOPSV Hierarchy"
code "betrixaban": '1592988' from E."OMOPSV Hierarchy"
code "bivalirudin": '19084670' from E."OMOPSV Hierarchy"
code "certoparin": '19016072' from E."OMOPSV Hierarchy"
code "Clorindione": '40798763' from E."OMOPSV Hierarchy"
code "dabigatran etexilate": '40228152' from E."OMOPSV Hierarchy"
code "dalteparin": '1301065' from E."OMOPSV Hierarchy"
code "danaparoid": '19026343' from E."OMOPSV Hierarchy"
code "desirudin": '19011712' from E."OMOPSV Hierarchy"
code "dicumarol": '1325124' from E."OMOPSV Hierarchy"
code "edoxaban": '45892847' from E."OMOPSV Hierarchy"
code "enoxaparin": '1301025' from E."OMOPSV Hierarchy"
code "fluindione": '19113013' from E."OMOPSV Hierarchy"
code "fondaparinux": '1315865' from E."OMOPSV Hierarchy"
code "heparin": '1367571' from E."OMOPSV Hierarchy"
code "lepirudin": '19092139' from E."OMOPSV Hierarchy"
code "Melagatran": '40798953' from E."OMOPSV Hierarchy"
code "nadroparin": '19001014' from E."OMOPSV Hierarchy"
code "parnaparin": '19008276' from E."OMOPSV Hierarchy"
code "phenindione": '19033934' from E."OMOPSV Hierarchy"
code "phenprocoumon": '19035344' from E."OMOPSV Hierarchy"
code "reviparin": '19129274' from E."OMOPSV Hierarchy"
code "rivaroxaban": '40241331' from E."OMOPSV Hierarchy"
code "sulodexide": '43009029' from E."OMOPSV Hierarchy"
code "tinzaparin": '1308473' from E."OMOPSV Hierarchy"
code "tioclomarol": '19018364' from E."OMOPSV Hierarchy"
code "warfarin": '1310149' from E."OMOPSV Hierarchy"
code "Ximelagatran": '40799186' from E."OMOPSV Hierarchy"

concept "Anticoagulation Drugs": {
  "acenocoumarol",
  "apixaban",
  "argatroban",
  "bemiparin",
  "betrixaban",
  "bivalirudin",
  "certoparin",
  "Clorindione",
  "dabigatran etexilate",
  "dalteparin",
  "danaparoid",
  "desirudin",
  "dicumarol",
  "edoxaban",
  "enoxaparin",
  "fluindione",
  "fondaparinux",
  "heparin",
  "lepirudin",
  "Melagatran",
  "nadroparin",
  "parnaparin",
  "phenindione",
  "phenprocoumon",
  "reviparin",
  "rivaroxaban",
  "sulodexide",
  "tinzaparin",
  "tioclomarol",
  "warfarin",
  "Ximelagatran"
}
